// The Track-B wire contract for the arqtos Authenticator connector class:
// establishing WHO IS DRIVING THIS SESSION, interactively and verifiably.
//
// This file is the contract for provider authors who will never read the Go
// SDK — including authors writing in another language. Everything a host relies
// on is stated here rather than only in the Go doc comments of the reference
// implementation. If the two ever disagree, this file is what the wire actually
// carries.
//
// # This is not the Roster class, and the difference is the failure mode
//
// A Roster reads a directory with a service credential and answers "who
// exists". This class asks "who is here right now, and did they prove it". A
// failed directory read is a stale roster. A FAILED AUTHENTICATION IS A SESSION
// THAT MUST NOT START.
//
// # The host owns the browser and the loopback listener
//
// The provider never opens a browser and never binds a port. Begin returns an
// authorization URL and an opaque handle; the host drives the operator's
// browser, receives the authorization code on ITS OWN redirect listener, and
// passes that code back to Complete.
//
// This is not a wiring preference. The connector contract's second invariant is
// passthrough-prohibited: a connector never forwards a raw credential to another
// party. A provider that obtained the operator's token and handed it onward
// would be brokering a credential for a third party. Putting a listener inside
// a third-party subprocess changes the trust boundary rather than the wiring.
//
// The SINGLE credential-shaped value crossing host to provider is the
// authorization code, and that is unavoidable — the host receives it and the
// provider must exchange it. It is acceptable because the code is single-use,
// short-lived, PKCE-bound, and useless without the verifier the provider holds.
//
// # Nothing obtained from the exchange crosses back
//
// Assertion below carries an identifier and two booleans. THERE IS NO FIELD FOR
// A TOKEN, an id token, or a raw claim set, and adding one would be a change to
// a published contract rather than an extension of it. Passthrough is
// unrepresentable on this wire rather than merely discouraged.
//
// # A rejected assertion is a status error, never a successful anonymous answer
//
// If verification fails — signature, issuer, audience, nonce, expiry — return a
// gRPC status error (UNAUTHENTICATED / PERMISSION_DENIED as applicable). DO NOT
// return an Assertion with authenticated = false.
//
// authenticated = false is a real answer, and it means the provider ANSWERED
// and identified the caller as nobody. Reaching it because verification failed
// reports ATTACKER-SUPPLIED INPUT as a legitimate anonymous session, and
// nothing downstream questions it because it arrived with no error.
//
// ⚠️ proto3 defaults a bool to false and does not put a false field on the wire
// at all. So the rejected-reported-as-anonymous shape is exactly what a
// provider produces by returning an empty message on a path it forgot to fail.
// That is why this is stated here rather than left to the Go implementation.
//
// # There is no capability on this wire
//
// The Authenticator class has an EMPTY capability vocabulary at v1. A
// device-code path, a machine-principal path, a refresh path and a step-up path
// were each identified and not added, because a capability nothing gates on is
// a speculative feature flag. The Capabilities RPC exists because it is part of
// the base contract every class shares, and a host reads it once at dial time;
// a provider declaring any capability for this class is refused.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authenticator.proto

package connectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Challenge is what a host needs in order to send the operator to the identity
// provider, and nothing more.
type Challenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where the host sends the operator's browser.
	//
	// An empty value is refused by the host: it has nowhere to send them, and
	// proto3's default for a string is exactly what a provider that forgot to set
	// it produces.
	AuthorizationUrl string `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	// An OPAQUE reference to the exchange this challenge began. The host passes
	// it back to Complete and never parses it.
	//
	// ⚠️ It is NOT the PKCE verifier and NOT the nonce. Those live in the
	// provider's own memory against this handle and are destroyed when the handle
	// is consumed or Close is called. A handle carrying the verifier would put
	// the one value that makes the authorization code useless into the same place
	// as the code.
	Handle        string `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_authenticator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_authenticator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{0}
}

func (x *Challenge) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *Challenge) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

// Assertion is the answer to "who is driving this session", after the provider
// has verified it.
//
// ⚠️ THREE FIELDS, AND NO FOURTH. There is deliberately no token, no id token
// and no claim set here — see the file header.
type Assertion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The provider's STABLE identifier for the operator — the same identifier
	// space a Roster reports in Principal.id, so a host can join a
	// just-authenticated operator onto the groups a directory reports.
	//
	// If the two report different spaces the join silently matches nobody while
	// every individual call succeeds. A vendor shipping both connectors is
	// expected to pin the correspondence with a test against a shared fixture.
	PrincipalId string `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	// Whether the provider verified the operator.
	//
	// This field and principal_id must AGREE: authenticated = true with an empty
	// principal_id is a success that identifies no one, and a principal_id while
	// authenticated is false is a name nothing verified. A host refuses both
	// shapes as contract faults.
	Authenticated bool `protobuf:"varint,2,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	// Whether the provider considers this principal currently enabled.
	//
	// active = false with authenticated = true is a REAL ANSWER — a verified
	// principal who is suspended, on leave or mid-transfer — and the host decides
	// what to do with it. Do not raise it as an error: doing so removes the
	// host's ability to tell "suspended" from "could not authenticate", which are
	// different sessions.
	//
	// ⚠️ proto3 defaults a bool to false, so a provider that never sets this
	// reports every verified principal as disabled. The direction that costs more
	// is the other one — reporting a disabled principal as enabled — so set it
	// from what the provider actually said, never from a default.
	Active        bool `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assertion) Reset() {
	*x = Assertion{}
	mi := &file_authenticator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assertion) ProtoMessage() {}

func (x *Assertion) ProtoReflect() protoreflect.Message {
	mi := &file_authenticator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assertion.ProtoReflect.Descriptor instead.
func (*Assertion) Descriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{1}
}

func (x *Assertion) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *Assertion) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *Assertion) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type BeginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRequest) Reset() {
	*x = BeginRequest{}
	mi := &file_authenticator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRequest) ProtoMessage() {}

func (x *BeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authenticator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRequest.ProtoReflect.Descriptor instead.
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{2}
}

type BeginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     *Challenge             `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginResponse) Reset() {
	*x = BeginResponse{}
	mi := &file_authenticator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginResponse) ProtoMessage() {}

func (x *BeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authenticator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginResponse.ProtoReflect.Descriptor instead.
func (*BeginResponse) Descriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{3}
}

func (x *BeginResponse) GetChallenge() *Challenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type CompleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The handle from the Challenge this exchange began with.
	//
	// A handle the provider never issued, one already consumed, and one that has
	// expired are three DISTINGUISHABLE outcomes, and none of them is a
	// successful anonymous assertion. INVALID_ARGUMENT is the classification for
	// all three; the message distinguishes them for an operator.
	Handle string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// The authorization code the host received on its own redirect listener.
	//
	// ⚠️ This is the one credential-shaped value on this wire, and it travels in
	// this direction only. Do not log it, do not persist it, and do not return
	// anything derived from it.
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_authenticator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authenticator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *CompleteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assertion     *Assertion             `protobuf:"bytes,1,opt,name=assertion,proto3" json:"assertion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_authenticator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authenticator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteResponse) GetAssertion() *Assertion {
	if x != nil {
		return x.Assertion
	}
	return nil
}

var File_authenticator_proto protoreflect.FileDescriptor

const file_authenticator_proto_rawDesc = "" +
	"\n" +
	"\x13authenticator.proto\x12\fconnector.v1\x1a\x0fconnector.proto\"P\n" +
	"\tChallenge\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\"l\n" +
	"\tAssertion\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12$\n" +
	"\rauthenticated\x18\x02 \x01(\bR\rauthenticated\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"\x0e\n" +
	"\fBeginRequest\"F\n" +
	"\rBeginResponse\x125\n" +
	"\tchallenge\x18\x01 \x01(\v2\x17.connector.v1.ChallengeR\tchallenge\"=\n" +
	"\x0fCompleteRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"I\n" +
	"\x10CompleteResponse\x125\n" +
	"\tassertion\x18\x01 \x01(\v2\x17.connector.v1.AssertionR\tassertion2\xfa\x02\n" +
	"\rAuthenticator\x12@\n" +
	"\x05Begin\x12\x1a.connector.v1.BeginRequest\x1a\x1b.connector.v1.BeginResponse\x12I\n" +
	"\bComplete\x12\x1d.connector.v1.CompleteRequest\x1a\x1e.connector.v1.CompleteResponse\x12C\n" +
	"\x06Health\x12\x1b.connector.v1.HealthRequest\x1a\x1c.connector.v1.HealthResponse\x12U\n" +
	"\fCapabilities\x12!.connector.v1.CapabilitiesRequest\x1a\".connector.v1.CapabilitiesResponse\x12@\n" +
	"\x05Close\x12\x1a.connector.v1.CloseRequest\x1a\x1b.connector.v1.CloseResponseB.Z,github.com/arqtiqa/arqtos-sdk-go/connectorpbb\x06proto3"

var (
	file_authenticator_proto_rawDescOnce sync.Once
	file_authenticator_proto_rawDescData []byte
)

func file_authenticator_proto_rawDescGZIP() []byte {
	file_authenticator_proto_rawDescOnce.Do(func() {
		file_authenticator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authenticator_proto_rawDesc), len(file_authenticator_proto_rawDesc)))
	})
	return file_authenticator_proto_rawDescData
}

var file_authenticator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_authenticator_proto_goTypes = []any{
	(*Challenge)(nil),            // 0: connector.v1.Challenge
	(*Assertion)(nil),            // 1: connector.v1.Assertion
	(*BeginRequest)(nil),         // 2: connector.v1.BeginRequest
	(*BeginResponse)(nil),        // 3: connector.v1.BeginResponse
	(*CompleteRequest)(nil),      // 4: connector.v1.CompleteRequest
	(*CompleteResponse)(nil),     // 5: connector.v1.CompleteResponse
	(*HealthRequest)(nil),        // 6: connector.v1.HealthRequest
	(*CapabilitiesRequest)(nil),  // 7: connector.v1.CapabilitiesRequest
	(*CloseRequest)(nil),         // 8: connector.v1.CloseRequest
	(*HealthResponse)(nil),       // 9: connector.v1.HealthResponse
	(*CapabilitiesResponse)(nil), // 10: connector.v1.CapabilitiesResponse
	(*CloseResponse)(nil),        // 11: connector.v1.CloseResponse
}
var file_authenticator_proto_depIdxs = []int32{
	0,  // 0: connector.v1.BeginResponse.challenge:type_name -> connector.v1.Challenge
	1,  // 1: connector.v1.CompleteResponse.assertion:type_name -> connector.v1.Assertion
	2,  // 2: connector.v1.Authenticator.Begin:input_type -> connector.v1.BeginRequest
	4,  // 3: connector.v1.Authenticator.Complete:input_type -> connector.v1.CompleteRequest
	6,  // 4: connector.v1.Authenticator.Health:input_type -> connector.v1.HealthRequest
	7,  // 5: connector.v1.Authenticator.Capabilities:input_type -> connector.v1.CapabilitiesRequest
	8,  // 6: connector.v1.Authenticator.Close:input_type -> connector.v1.CloseRequest
	3,  // 7: connector.v1.Authenticator.Begin:output_type -> connector.v1.BeginResponse
	5,  // 8: connector.v1.Authenticator.Complete:output_type -> connector.v1.CompleteResponse
	9,  // 9: connector.v1.Authenticator.Health:output_type -> connector.v1.HealthResponse
	10, // 10: connector.v1.Authenticator.Capabilities:output_type -> connector.v1.CapabilitiesResponse
	11, // 11: connector.v1.Authenticator.Close:output_type -> connector.v1.CloseResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_authenticator_proto_init() }
func file_authenticator_proto_init() {
	if File_authenticator_proto != nil {
		return
	}
	file_connector_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authenticator_proto_rawDesc), len(file_authenticator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authenticator_proto_goTypes,
		DependencyIndexes: file_authenticator_proto_depIdxs,
		MessageInfos:      file_authenticator_proto_msgTypes,
	}.Build()
	File_authenticator_proto = out.File
	file_authenticator_proto_goTypes = nil
	file_authenticator_proto_depIdxs = nil
}
