// The Track-B wire contract for the arqtos Authenticator connector class:
// establishing WHO IS DRIVING THIS SESSION, interactively and verifiably.
//
// This file is the contract for provider authors who will never read the Go
// SDK — including authors writing in another language. Everything a host relies
// on is stated here rather than only in the Go doc comments of the reference
// implementation. If the two ever disagree, this file is what the wire actually
// carries.
//
// # This is not the Roster class, and the difference is the failure mode
//
// A Roster reads a directory with a service credential and answers "who
// exists". This class asks "who is here right now, and did they prove it". A
// failed directory read is a stale roster. A FAILED AUTHENTICATION IS A SESSION
// THAT MUST NOT START.
//
// # The host owns the browser and the loopback listener
//
// The provider never opens a browser and never binds a port. Begin returns an
// authorization URL and an opaque handle; the host drives the operator's
// browser, receives the authorization code on ITS OWN redirect listener, and
// passes that code back to Complete.
//
// This is not a wiring preference. The connector contract's second invariant is
// passthrough-prohibited: a connector never forwards a raw credential to another
// party. A provider that obtained the operator's token and handed it onward
// would be brokering a credential for a third party. Putting a listener inside
// a third-party subprocess changes the trust boundary rather than the wiring.
//
// The SINGLE credential-shaped value crossing host to provider is the
// authorization code, and that is unavoidable — the host receives it and the
// provider must exchange it. It is acceptable because the code is single-use,
// short-lived, PKCE-bound, and useless without the verifier the provider holds.
//
// # Nothing obtained from the exchange crosses back
//
// Assertion below carries an identifier and two booleans. THERE IS NO FIELD FOR
// A TOKEN, an id token, or a raw claim set, and adding one would be a change to
// a published contract rather than an extension of it. Passthrough is
// unrepresentable on this wire rather than merely discouraged.
//
// # A rejected assertion is a status error, never a successful anonymous answer
//
// If verification fails — signature, issuer, audience, nonce, expiry — return a
// gRPC status error (UNAUTHENTICATED / PERMISSION_DENIED as applicable). DO NOT
// return an Assertion with authenticated = false.
//
// authenticated = false is a real answer, and it means the provider ANSWERED
// and identified the caller as nobody. Reaching it because verification failed
// reports ATTACKER-SUPPLIED INPUT as a legitimate anonymous session, and
// nothing downstream questions it because it arrived with no error.
//
// ⚠️ proto3 defaults a bool to false and does not put a false field on the wire
// at all. So the rejected-reported-as-anonymous shape is exactly what a
// provider produces by returning an empty message on a path it forgot to fail.
// That is why this is stated here rather than left to the Go implementation.
//
// # There is no capability on this wire
//
// The Authenticator class has an EMPTY capability vocabulary at v1. A
// device-code path, a machine-principal path, a refresh path and a step-up path
// were each identified and not added, because a capability nothing gates on is
// a speculative feature flag. The Capabilities RPC exists because it is part of
// the base contract every class shares, and a host reads it once at dial time;
// a provider declaring any capability for this class is refused.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: authenticator.proto

package connectorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Authenticator_Begin_FullMethodName        = "/connector.v1.Authenticator/Begin"
	Authenticator_Complete_FullMethodName     = "/connector.v1.Authenticator/Complete"
	Authenticator_Health_FullMethodName       = "/connector.v1.Authenticator/Health"
	Authenticator_Capabilities_FullMethodName = "/connector.v1.Authenticator/Capabilities"
	Authenticator_Close_FullMethodName        = "/connector.v1.Authenticator/Close"
)

// AuthenticatorClient is the client API for Authenticator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenticatorClient interface {
	// Begin starts an exchange and returns the Challenge the host needs to drive
	// it.
	//
	// The provider generates and retains the PKCE verifier and the nonce against
	// the returned handle. It does NOT open a browser and does NOT bind a
	// listener; the host does both.
	Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (*BeginResponse, error)
	// Complete exchanges the authorization code, VERIFIES the result, and returns
	// the Assertion.
	//
	// Before returning anything it must verify the signature against the
	// provider's key set (key selected by the assertion's own key id, key set
	// fetched from the discovery document rather than pinned), the issuer, the
	// audience, the nonce issued with this handle, and expiry.
	//
	// ⚠️ Any of those failing is a STATUS ERROR, never an Assertion with
	// authenticated = false. See the file header for why that shape is the worst
	// outcome available to this class.
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	// Health reports reachability of the identity provider.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Capabilities lists what this connector supports. The Authenticator class's
	// vocabulary is EMPTY at v1, so a conformant provider returns nothing here. A
	// host reads this ONCE, at dial time.
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// Close releases what the provider holds — in-flight handles and the
	// verifiers and nonces held against them. It is idempotent.
	//
	// ⚠️ Every handle and every verifier must be destroyed here. Process teardown
	// is the host's go-plugin client Kill(); this call is the provider's own
	// chance to release first, and a verifier outliving the session is a
	// credential outliving the session.
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
}

type authenticatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticatorClient(cc grpc.ClientConnInterface) AuthenticatorClient {
	return &authenticatorClient{cc}
}

func (c *authenticatorClient) Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (*BeginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginResponse)
	err := c.cc.Invoke(ctx, Authenticator_Begin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticatorClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, Authenticator_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticatorClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Authenticator_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticatorClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, Authenticator_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticatorClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, Authenticator_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticatorServer is the server API for Authenticator service.
// All implementations must embed UnimplementedAuthenticatorServer
// for forward compatibility.
type AuthenticatorServer interface {
	// Begin starts an exchange and returns the Challenge the host needs to drive
	// it.
	//
	// The provider generates and retains the PKCE verifier and the nonce against
	// the returned handle. It does NOT open a browser and does NOT bind a
	// listener; the host does both.
	Begin(context.Context, *BeginRequest) (*BeginResponse, error)
	// Complete exchanges the authorization code, VERIFIES the result, and returns
	// the Assertion.
	//
	// Before returning anything it must verify the signature against the
	// provider's key set (key selected by the assertion's own key id, key set
	// fetched from the discovery document rather than pinned), the issuer, the
	// audience, the nonce issued with this handle, and expiry.
	//
	// ⚠️ Any of those failing is a STATUS ERROR, never an Assertion with
	// authenticated = false. See the file header for why that shape is the worst
	// outcome available to this class.
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	// Health reports reachability of the identity provider.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Capabilities lists what this connector supports. The Authenticator class's
	// vocabulary is EMPTY at v1, so a conformant provider returns nothing here. A
	// host reads this ONCE, at dial time.
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	// Close releases what the provider holds — in-flight handles and the
	// verifiers and nonces held against them. It is idempotent.
	//
	// ⚠️ Every handle and every verifier must be destroyed here. Process teardown
	// is the host's go-plugin client Kill(); this call is the provider's own
	// chance to release first, and a verifier outliving the session is a
	// credential outliving the session.
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	mustEmbedUnimplementedAuthenticatorServer()
}

// UnimplementedAuthenticatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthenticatorServer struct{}

func (UnimplementedAuthenticatorServer) Begin(context.Context, *BeginRequest) (*BeginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Begin not implemented")
}
func (UnimplementedAuthenticatorServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedAuthenticatorServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAuthenticatorServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedAuthenticatorServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedAuthenticatorServer) mustEmbedUnimplementedAuthenticatorServer() {}
func (UnimplementedAuthenticatorServer) testEmbeddedByValue()                       {}

// UnsafeAuthenticatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenticatorServer will
// result in compilation errors.
type UnsafeAuthenticatorServer interface {
	mustEmbedUnimplementedAuthenticatorServer()
}

func RegisterAuthenticatorServer(s grpc.ServiceRegistrar, srv AuthenticatorServer) {
	// If the following call panics, it indicates UnimplementedAuthenticatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Authenticator_ServiceDesc, srv)
}

func _Authenticator_Begin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).Begin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authenticator_Begin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).Begin(ctx, req.(*BeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticator_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authenticator_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticator_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authenticator_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticator_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authenticator_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authenticator_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticatorServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authenticator_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticatorServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authenticator_ServiceDesc is the grpc.ServiceDesc for Authenticator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authenticator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connector.v1.Authenticator",
	HandlerType: (*AuthenticatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Begin",
			Handler:    _Authenticator_Begin_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _Authenticator_Complete_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Authenticator_Health_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _Authenticator_Capabilities_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Authenticator_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authenticator.proto",
}
