// The Track-B wire contract for the arqtos Certificate connector class:
// data goes in, a signature comes back, and private key material never leaves.
//
// This file is the contract for provider authors who will never read the Go
// SDK. If the Go interface and this file disagree, this file is what the
// wire actually carries.
//
// # The inverted invariant
//
// CredentialLoader is defined by material LEAVING the backend. This class is
// defined by material NEVER leaving: a host sends bytes, a signature comes
// back. There is no Export RPC, and adding one is a contract change that
// TestCertificateServiceHasNoExport must catch (arqtos-sdk-go#138).
//
// # Verify failures are status errors, never a successful "invalid" answer
//
// A missing key is NOT_FOUND. A signature that does not match is
// INVALID_ARGUMENT. Do not return an empty success for a tampered payload.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: certificate.proto

package connectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *SignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_certificate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{1}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_certificate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *VerifyRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VerifyRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_certificate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{3}
}

type PublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyRequest) Reset() {
	*x = PublicKeyRequest{}
	mi := &file_certificate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyRequest) ProtoMessage() {}

func (x *PublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyRequest.ProtoReflect.Descriptor instead.
func (*PublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{4}
}

func (x *PublicKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type PublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyResponse) Reset() {
	*x = PublicKeyResponse{}
	mi := &file_certificate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyResponse) ProtoMessage() {}

func (x *PublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyResponse.ProtoReflect.Descriptor instead.
func (*PublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_certificate_proto_rawDescGZIP(), []int{5}
}

func (x *PublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PublicKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

var File_certificate_proto protoreflect.FileDescriptor

const file_certificate_proto_rawDesc = "" +
	"\n" +
	"\x11certificate.proto\x12\fconnector.v1\x1a\x0fconnector.proto\">\n" +
	"\vSignRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"J\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\"^\n" +
	"\rVerifyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x10\n" +
	"\x0eVerifyResponse\")\n" +
	"\x10PublicKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"P\n" +
	"\x11PublicKeyResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm2\xbd\x03\n" +
	"\vCertificate\x12=\n" +
	"\x04Sign\x12\x19.connector.v1.SignRequest\x1a\x1a.connector.v1.SignResponse\x12C\n" +
	"\x06Verify\x12\x1b.connector.v1.VerifyRequest\x1a\x1c.connector.v1.VerifyResponse\x12L\n" +
	"\tPublicKey\x12\x1e.connector.v1.PublicKeyRequest\x1a\x1f.connector.v1.PublicKeyResponse\x12C\n" +
	"\x06Health\x12\x1b.connector.v1.HealthRequest\x1a\x1c.connector.v1.HealthResponse\x12U\n" +
	"\fCapabilities\x12!.connector.v1.CapabilitiesRequest\x1a\".connector.v1.CapabilitiesResponse\x12@\n" +
	"\x05Close\x12\x1a.connector.v1.CloseRequest\x1a\x1b.connector.v1.CloseResponseB.Z,github.com/arqtiqa/arqtos-sdk-go/connectorpbb\x06proto3"

var (
	file_certificate_proto_rawDescOnce sync.Once
	file_certificate_proto_rawDescData []byte
)

func file_certificate_proto_rawDescGZIP() []byte {
	file_certificate_proto_rawDescOnce.Do(func() {
		file_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_certificate_proto_rawDesc), len(file_certificate_proto_rawDesc)))
	})
	return file_certificate_proto_rawDescData
}

var file_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_certificate_proto_goTypes = []any{
	(*SignRequest)(nil),          // 0: connector.v1.SignRequest
	(*SignResponse)(nil),         // 1: connector.v1.SignResponse
	(*VerifyRequest)(nil),        // 2: connector.v1.VerifyRequest
	(*VerifyResponse)(nil),       // 3: connector.v1.VerifyResponse
	(*PublicKeyRequest)(nil),     // 4: connector.v1.PublicKeyRequest
	(*PublicKeyResponse)(nil),    // 5: connector.v1.PublicKeyResponse
	(*HealthRequest)(nil),        // 6: connector.v1.HealthRequest
	(*CapabilitiesRequest)(nil),  // 7: connector.v1.CapabilitiesRequest
	(*CloseRequest)(nil),         // 8: connector.v1.CloseRequest
	(*HealthResponse)(nil),       // 9: connector.v1.HealthResponse
	(*CapabilitiesResponse)(nil), // 10: connector.v1.CapabilitiesResponse
	(*CloseResponse)(nil),        // 11: connector.v1.CloseResponse
}
var file_certificate_proto_depIdxs = []int32{
	0,  // 0: connector.v1.Certificate.Sign:input_type -> connector.v1.SignRequest
	2,  // 1: connector.v1.Certificate.Verify:input_type -> connector.v1.VerifyRequest
	4,  // 2: connector.v1.Certificate.PublicKey:input_type -> connector.v1.PublicKeyRequest
	6,  // 3: connector.v1.Certificate.Health:input_type -> connector.v1.HealthRequest
	7,  // 4: connector.v1.Certificate.Capabilities:input_type -> connector.v1.CapabilitiesRequest
	8,  // 5: connector.v1.Certificate.Close:input_type -> connector.v1.CloseRequest
	1,  // 6: connector.v1.Certificate.Sign:output_type -> connector.v1.SignResponse
	3,  // 7: connector.v1.Certificate.Verify:output_type -> connector.v1.VerifyResponse
	5,  // 8: connector.v1.Certificate.PublicKey:output_type -> connector.v1.PublicKeyResponse
	9,  // 9: connector.v1.Certificate.Health:output_type -> connector.v1.HealthResponse
	10, // 10: connector.v1.Certificate.Capabilities:output_type -> connector.v1.CapabilitiesResponse
	11, // 11: connector.v1.Certificate.Close:output_type -> connector.v1.CloseResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_certificate_proto_init() }
func file_certificate_proto_init() {
	if File_certificate_proto != nil {
		return
	}
	file_connector_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certificate_proto_rawDesc), len(file_certificate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_certificate_proto_goTypes,
		DependencyIndexes: file_certificate_proto_depIdxs,
		MessageInfos:      file_certificate_proto_msgTypes,
	}.Build()
	File_certificate_proto = out.File
	file_certificate_proto_goTypes = nil
	file_certificate_proto_depIdxs = nil
}
