// The Track-B wire contract for the arqtos CredentialLoader connector class.
//
// This file is the contract for provider authors who will never read the Go
// SDK — including authors writing in another language. Everything a host
// relies on is stated here, in this file, rather than only in the Go doc
// comments of the reference implementation. If the two ever disagree, this
// file is what the wire actually carries.
//
// # The one rule that matters most
//
// A credential that DID NOT RESOLVE must never reach a host looking like a
// credential whose value is empty. That conflation is the bug this whole
// contract exists to prevent: a signed-out secret backend typically prints
// NOTHING and exits 0, and a provider that forwards that faithfully as a
// success hands the host "" — which then authenticates with an empty
// password instead of failing.
//
// So on this wire, "I resolved nothing" and "I resolved a value that is
// genuinely empty" have DIFFERENT encodings, and the accidental encoding —
// whatever a provider naturally emits when it has nothing — always means
// "resolved nothing", which is the safe reading. See Material below.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: credentialloader.proto

package connectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ref is an op://<vault>/<item>/<field> secret reference: the ADDRESS of a
// secret, never the secret itself. All three segments are required and
// non-empty; a host sends only refs, and a provider returns only the material
// for the ref it was asked about.
type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_credentialloader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{0}
}

func (x *Ref) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *Ref) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Ref) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

// Material is resolved secret material, and the presence rules below are the
// contract's load-bearing part.
//
// Read the three cases as a WHOLE MESSAGE, not as a bytes field:
//
//  1. NO Material message at all (the containing field is unset)
//     -> nothing was resolved. The host treats this as a failure and refuses
//     to produce a readable credential from it.
//
//  2. Material with `value` non-empty
//     -> that is the secret. `empty_by_assertion` is ignored here; bytes
//     present always mean a resolved value.
//
//  3. Material with no `value` bytes AND `empty_by_assertion = true`
//     -> the provider ASSERTS the stored secret is genuinely, intentionally
//     empty. The host produces a readable credential of length zero.
//
//  4. Material with no `value` bytes and NO `empty_by_assertion`
//     -> nothing was resolved. Identical to case 1. This is deliberate: it
//     is the encoding a provider produces by accident (an unset struct,
//     a default-constructed message, a "" it forwarded from a backend),
//     and the accidental encoding must have the SAFE meaning.
//
// Note that proto3 does not put a zero-length `bytes` field on the wire at
// all, so cases 3 and 4 differ ONLY by the boolean. That is exactly why the
// boolean exists: without it, a conformant "deliberately empty" and a rogue
// "I got nothing" are byte-identical and the host cannot tell them apart.
type Material struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The secret bytes. Empty or absent means NO VALUE unless
	// empty_by_assertion is set — see the message comment above.
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Set this ONLY to assert "this credential is deliberately, genuinely
	// empty". Set it only if your backend can distinguish a STORED EMPTY VALUE
	// from an unauthenticated, missing, or failed read. If it cannot make that
	// distinction, you have a failure on your hands, not an empty secret:
	// return a gRPC status error instead (see the error mapping below).
	//
	// Absent bytes WITHOUT this flag means nothing was resolved, and the host
	// refuses it — naming your connector in the fault it reports.
	EmptyByAssertion bool `protobuf:"varint,2,opt,name=empty_by_assertion,json=emptyByAssertion,proto3" json:"empty_by_assertion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_credentialloader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{1}
}

func (x *Material) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Material) GetEmptyByAssertion() bool {
	if x != nil {
		return x.EmptyByAssertion
	}
	return false
}

// Lease describes a dynamic, time-bounded secret's validity window.
type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Renewable     bool                   `protobuf:"varint,4,opt,name=renewable,proto3" json:"renewable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_credentialloader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{2}
}

func (x *Lease) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lease) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Lease) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Lease) GetRenewable() bool {
	if x != nil {
		return x.Renewable
	}
	return false
}

// Failure is ONE reference's typed failure inside a batch response.
//
// A whole-call failure is a gRPC status error on the RPC itself. This message
// exists because a batch RPC that SUCCEEDED can still carry a per-reference
// failure, and one missing field must not discard the other ninety-nine
// values fetched with it.
//
// `code` is a google.rpc.Code / gRPC status code number, carrying the same
// classification a single Resolve would return as a status error; `message`
// is the human-readable detail. A host maps the code back into its closed
// error vocabulary, so it acts on the classification and never on the text.
//
// MUST NOT contain secret material: unlike Material, failure text crosses the
// wire verbatim and a host may write it to an audit log.
type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_credentialloader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{3}
}

func (x *Failure) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_credentialloader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

// ResolveResponse carries the resolved material, subject to Material's
// presence rules. An UNSET material field means nothing was resolved; it is
// the correct way to say so alongside a non-error response, though returning
// a gRPC status error is better still because it also says WHY.
type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_credentialloader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveResponse) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_credentialloader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// ListResponse returns REFERENCES ONLY. A List must never resolve material
// for the entries it enumerates.
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*Ref                 `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_credentialloader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetRefs() []*Ref {
	if x != nil {
		return x.Refs
	}
	return nil
}

type LeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_credentialloader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{8}
}

func (x *LeaseRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

// LeaseResponse carries the leased material — same Material presence rules as
// ResolveResponse — plus the lease describing its validity window.
type LeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	Lease         *Lease                 `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseResponse) Reset() {
	*x = LeaseResponse{}
	mi := &file_credentialloader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseResponse) ProtoMessage() {}

func (x *LeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseResponse.ProtoReflect.Descriptor instead.
func (*LeaseResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{9}
}

func (x *LeaseResponse) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *LeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_credentialloader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{10}
}

func (x *RenewRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_credentialloader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{11}
}

func (x *RenewResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_credentialloader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_credentialloader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{13}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_credentialloader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{14}
}

// HealthResponse reports reachability of the backing store. `status` is
// 0 = healthy, 1 = degraded, 2 = unavailable.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_credentialloader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_credentialloader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{16}
}

// CapabilitiesResponse lists the optional behaviours this connector supports,
// drawn from the class's closed capability vocabulary — for CredentialLoader:
// "read", "lease", "rotate", "oidc", "approle", "batch_resolve".
//
// This list is load-bearing at DIAL TIME, not only for documentation: a host
// decides from it whether this provider can be asked to batch, and it must
// agree with the connector's shipped manifest. Declaring a capability the
// provider does not honour is worse than declaring nothing at all.
type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_credentialloader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{17}
}

func (x *CapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ResolveBatchRequest asks for many references in ONE call.
type ResolveBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*Ref                 `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveBatchRequest) Reset() {
	*x = ResolveBatchRequest{}
	mi := &file_credentialloader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBatchRequest) ProtoMessage() {}

func (x *ResolveBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBatchRequest.ProtoReflect.Descriptor instead.
func (*ResolveBatchRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{18}
}

func (x *ResolveBatchRequest) GetRefs() []*Ref {
	if x != nil {
		return x.Refs
	}
	return nil
}

// ResolveBatchResult is ONE requested reference's outcome: EXACTLY ONE of a
// resolved material or a typed failure, never both and never neither.
//
//   - `ref` echoes the reference this result answers, so a host can attribute
//     a result without relying on position alone. It is required.
//   - `material` follows Material's presence rules exactly, including
//     `empty_by_assertion`. Absent-and-unasserted means nothing was resolved.
//   - `failure` is this reference's typed failure.
//
// A result carrying NEITHER — no failure, and no material or an unasserted
// empty one — is a contract violation the host reports against your
// connector by name. It is not read as an empty credential.
type ResolveBatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Material      *Material              `protobuf:"bytes,2,opt,name=material,proto3" json:"material,omitempty"`
	Failure       *Failure               `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveBatchResult) Reset() {
	*x = ResolveBatchResult{}
	mi := &file_credentialloader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBatchResult) ProtoMessage() {}

func (x *ResolveBatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBatchResult.ProtoReflect.Descriptor instead.
func (*ResolveBatchResult) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{19}
}

func (x *ResolveBatchResult) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ResolveBatchResult) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *ResolveBatchResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

// ResolveBatchResponse returns EXACTLY ONE result per requested reference, IN
// THE REQUESTED ORDER. A host verifies both, and refuses the whole batch if
// either is wrong: it cannot attribute mismatched results to the references
// it asked about, and guessing the correspondence is how the wrong secret
// reaches the wrong caller.
type ResolveBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ResolveBatchResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveBatchResponse) Reset() {
	*x = ResolveBatchResponse{}
	mi := &file_credentialloader_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBatchResponse) ProtoMessage() {}

func (x *ResolveBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBatchResponse.ProtoReflect.Descriptor instead.
func (*ResolveBatchResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{20}
}

func (x *ResolveBatchResponse) GetResults() []*ResolveBatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_credentialloader_proto protoreflect.FileDescriptor

const file_credentialloader_proto_rawDesc = "" +
	"\n" +
	"\x16credentialloader.proto\x12\fconnector.v1\"E\n" +
	"\x03Ref\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\"N\n" +
	"\bMaterial\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12,\n" +
	"\x12empty_by_assertion\x18\x02 \x01(\bR\x10emptyByAssertion\"~\n" +
	"\x05Lease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12\x1c\n" +
	"\trenewable\x18\x04 \x01(\bR\trenewable\"7\n" +
	"\aFailure\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x0eResolveRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.connector.v1.RefR\x03ref\"E\n" +
	"\x0fResolveResponse\x122\n" +
	"\bmaterial\x18\x01 \x01(\v2\x16.connector.v1.MaterialR\bmaterial\"#\n" +
	"\vListRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"5\n" +
	"\fListResponse\x12%\n" +
	"\x04refs\x18\x01 \x03(\v2\x11.connector.v1.RefR\x04refs\"3\n" +
	"\fLeaseRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.connector.v1.RefR\x03ref\"n\n" +
	"\rLeaseResponse\x122\n" +
	"\bmaterial\x18\x01 \x01(\v2\x16.connector.v1.MaterialR\bmaterial\x12)\n" +
	"\x05lease\x18\x02 \x01(\v2\x13.connector.v1.LeaseR\x05lease\"9\n" +
	"\fRenewRequest\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.connector.v1.LeaseR\x05lease\":\n" +
	"\rRenewResponse\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.connector.v1.LeaseR\x05lease\":\n" +
	"\rRevokeRequest\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.connector.v1.LeaseR\x05lease\"\x10\n" +
	"\x0eRevokeResponse\"\x0f\n" +
	"\rHealthRequest\"@\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x15\n" +
	"\x13CapabilitiesRequest\":\n" +
	"\x14CapabilitiesResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"<\n" +
	"\x13ResolveBatchRequest\x12%\n" +
	"\x04refs\x18\x01 \x03(\v2\x11.connector.v1.RefR\x04refs\"\x9e\x01\n" +
	"\x12ResolveBatchResult\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.connector.v1.RefR\x03ref\x122\n" +
	"\bmaterial\x18\x02 \x01(\v2\x16.connector.v1.MaterialR\bmaterial\x12/\n" +
	"\afailure\x18\x03 \x01(\v2\x15.connector.v1.FailureR\afailure\"R\n" +
	"\x14ResolveBatchResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .connector.v1.ResolveBatchResultR\aresults2\xd5\x04\n" +
	"\x10CredentialLoader\x12F\n" +
	"\aResolve\x12\x1c.connector.v1.ResolveRequest\x1a\x1d.connector.v1.ResolveResponse\x12=\n" +
	"\x04List\x12\x19.connector.v1.ListRequest\x1a\x1a.connector.v1.ListResponse\x12@\n" +
	"\x05Lease\x12\x1a.connector.v1.LeaseRequest\x1a\x1b.connector.v1.LeaseResponse\x12@\n" +
	"\x05Renew\x12\x1a.connector.v1.RenewRequest\x1a\x1b.connector.v1.RenewResponse\x12C\n" +
	"\x06Revoke\x12\x1b.connector.v1.RevokeRequest\x1a\x1c.connector.v1.RevokeResponse\x12C\n" +
	"\x06Health\x12\x1b.connector.v1.HealthRequest\x1a\x1c.connector.v1.HealthResponse\x12U\n" +
	"\fCapabilities\x12!.connector.v1.CapabilitiesRequest\x1a\".connector.v1.CapabilitiesResponse\x12U\n" +
	"\fResolveBatch\x12!.connector.v1.ResolveBatchRequest\x1a\".connector.v1.ResolveBatchResponseB.Z,github.com/arqtiqa/arqtos-sdk-go/connectorpbb\x06proto3"

var (
	file_credentialloader_proto_rawDescOnce sync.Once
	file_credentialloader_proto_rawDescData []byte
)

func file_credentialloader_proto_rawDescGZIP() []byte {
	file_credentialloader_proto_rawDescOnce.Do(func() {
		file_credentialloader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credentialloader_proto_rawDesc), len(file_credentialloader_proto_rawDesc)))
	})
	return file_credentialloader_proto_rawDescData
}

var file_credentialloader_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_credentialloader_proto_goTypes = []any{
	(*Ref)(nil),                  // 0: connector.v1.Ref
	(*Material)(nil),             // 1: connector.v1.Material
	(*Lease)(nil),                // 2: connector.v1.Lease
	(*Failure)(nil),              // 3: connector.v1.Failure
	(*ResolveRequest)(nil),       // 4: connector.v1.ResolveRequest
	(*ResolveResponse)(nil),      // 5: connector.v1.ResolveResponse
	(*ListRequest)(nil),          // 6: connector.v1.ListRequest
	(*ListResponse)(nil),         // 7: connector.v1.ListResponse
	(*LeaseRequest)(nil),         // 8: connector.v1.LeaseRequest
	(*LeaseResponse)(nil),        // 9: connector.v1.LeaseResponse
	(*RenewRequest)(nil),         // 10: connector.v1.RenewRequest
	(*RenewResponse)(nil),        // 11: connector.v1.RenewResponse
	(*RevokeRequest)(nil),        // 12: connector.v1.RevokeRequest
	(*RevokeResponse)(nil),       // 13: connector.v1.RevokeResponse
	(*HealthRequest)(nil),        // 14: connector.v1.HealthRequest
	(*HealthResponse)(nil),       // 15: connector.v1.HealthResponse
	(*CapabilitiesRequest)(nil),  // 16: connector.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 17: connector.v1.CapabilitiesResponse
	(*ResolveBatchRequest)(nil),  // 18: connector.v1.ResolveBatchRequest
	(*ResolveBatchResult)(nil),   // 19: connector.v1.ResolveBatchResult
	(*ResolveBatchResponse)(nil), // 20: connector.v1.ResolveBatchResponse
}
var file_credentialloader_proto_depIdxs = []int32{
	0,  // 0: connector.v1.ResolveRequest.ref:type_name -> connector.v1.Ref
	1,  // 1: connector.v1.ResolveResponse.material:type_name -> connector.v1.Material
	0,  // 2: connector.v1.ListResponse.refs:type_name -> connector.v1.Ref
	0,  // 3: connector.v1.LeaseRequest.ref:type_name -> connector.v1.Ref
	1,  // 4: connector.v1.LeaseResponse.material:type_name -> connector.v1.Material
	2,  // 5: connector.v1.LeaseResponse.lease:type_name -> connector.v1.Lease
	2,  // 6: connector.v1.RenewRequest.lease:type_name -> connector.v1.Lease
	2,  // 7: connector.v1.RenewResponse.lease:type_name -> connector.v1.Lease
	2,  // 8: connector.v1.RevokeRequest.lease:type_name -> connector.v1.Lease
	0,  // 9: connector.v1.ResolveBatchRequest.refs:type_name -> connector.v1.Ref
	0,  // 10: connector.v1.ResolveBatchResult.ref:type_name -> connector.v1.Ref
	1,  // 11: connector.v1.ResolveBatchResult.material:type_name -> connector.v1.Material
	3,  // 12: connector.v1.ResolveBatchResult.failure:type_name -> connector.v1.Failure
	19, // 13: connector.v1.ResolveBatchResponse.results:type_name -> connector.v1.ResolveBatchResult
	4,  // 14: connector.v1.CredentialLoader.Resolve:input_type -> connector.v1.ResolveRequest
	6,  // 15: connector.v1.CredentialLoader.List:input_type -> connector.v1.ListRequest
	8,  // 16: connector.v1.CredentialLoader.Lease:input_type -> connector.v1.LeaseRequest
	10, // 17: connector.v1.CredentialLoader.Renew:input_type -> connector.v1.RenewRequest
	12, // 18: connector.v1.CredentialLoader.Revoke:input_type -> connector.v1.RevokeRequest
	14, // 19: connector.v1.CredentialLoader.Health:input_type -> connector.v1.HealthRequest
	16, // 20: connector.v1.CredentialLoader.Capabilities:input_type -> connector.v1.CapabilitiesRequest
	18, // 21: connector.v1.CredentialLoader.ResolveBatch:input_type -> connector.v1.ResolveBatchRequest
	5,  // 22: connector.v1.CredentialLoader.Resolve:output_type -> connector.v1.ResolveResponse
	7,  // 23: connector.v1.CredentialLoader.List:output_type -> connector.v1.ListResponse
	9,  // 24: connector.v1.CredentialLoader.Lease:output_type -> connector.v1.LeaseResponse
	11, // 25: connector.v1.CredentialLoader.Renew:output_type -> connector.v1.RenewResponse
	13, // 26: connector.v1.CredentialLoader.Revoke:output_type -> connector.v1.RevokeResponse
	15, // 27: connector.v1.CredentialLoader.Health:output_type -> connector.v1.HealthResponse
	17, // 28: connector.v1.CredentialLoader.Capabilities:output_type -> connector.v1.CapabilitiesResponse
	20, // 29: connector.v1.CredentialLoader.ResolveBatch:output_type -> connector.v1.ResolveBatchResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_credentialloader_proto_init() }
func file_credentialloader_proto_init() {
	if File_credentialloader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credentialloader_proto_rawDesc), len(file_credentialloader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credentialloader_proto_goTypes,
		DependencyIndexes: file_credentialloader_proto_depIdxs,
		MessageInfos:      file_credentialloader_proto_msgTypes,
	}.Build()
	File_credentialloader_proto = out.File
	file_credentialloader_proto_goTypes = nil
	file_credentialloader_proto_depIdxs = nil
}
