// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: credentialloader.proto

package connectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_credentialloader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{0}
}

func (x *Ref) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *Ref) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Ref) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type Material struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_credentialloader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{1}
}

func (x *Material) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Renewable     bool                   `protobuf:"varint,4,opt,name=renewable,proto3" json:"renewable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_credentialloader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{2}
}

func (x *Lease) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lease) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Lease) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Lease) GetRenewable() bool {
	if x != nil {
		return x.Renewable
	}
	return false
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_credentialloader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_credentialloader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveResponse) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_credentialloader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*Ref                 `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_credentialloader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetRefs() []*Ref {
	if x != nil {
		return x.Refs
	}
	return nil
}

type LeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_credentialloader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{7}
}

func (x *LeaseRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type LeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	Lease         *Lease                 `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseResponse) Reset() {
	*x = LeaseResponse{}
	mi := &file_credentialloader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseResponse) ProtoMessage() {}

func (x *LeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseResponse.ProtoReflect.Descriptor instead.
func (*LeaseResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{8}
}

func (x *LeaseResponse) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *LeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_credentialloader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{9}
}

func (x *RenewRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_credentialloader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{10}
}

func (x *RenewResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_credentialloader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_credentialloader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{12}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_credentialloader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_credentialloader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_credentialloader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{15}
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_credentialloader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{16}
}

func (x *CapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_credentialloader_proto protoreflect.FileDescriptor

const file_credentialloader_proto_rawDesc = "" +
	"\n" +
	"\x16credentialloader.proto\x12\fconnector.v1\"E\n" +
	"\x03Ref\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\" \n" +
	"\bMaterial\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"~\n" +
	"\x05Lease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12\x1c\n" +
	"\trenewable\x18\x04 \x01(\bR\trenewable\"5\n" +
	"\x0eResolveRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.connector.v1.RefR\x03ref\"E\n" +
	"\x0fResolveResponse\x122\n" +
	"\bmaterial\x18\x01 \x01(\v2\x16.connector.v1.MaterialR\bmaterial\"#\n" +
	"\vListRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"5\n" +
	"\fListResponse\x12%\n" +
	"\x04refs\x18\x01 \x03(\v2\x11.connector.v1.RefR\x04refs\"3\n" +
	"\fLeaseRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.connector.v1.RefR\x03ref\"n\n" +
	"\rLeaseResponse\x122\n" +
	"\bmaterial\x18\x01 \x01(\v2\x16.connector.v1.MaterialR\bmaterial\x12)\n" +
	"\x05lease\x18\x02 \x01(\v2\x13.connector.v1.LeaseR\x05lease\"9\n" +
	"\fRenewRequest\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.connector.v1.LeaseR\x05lease\":\n" +
	"\rRenewResponse\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.connector.v1.LeaseR\x05lease\":\n" +
	"\rRevokeRequest\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.connector.v1.LeaseR\x05lease\"\x10\n" +
	"\x0eRevokeResponse\"\x0f\n" +
	"\rHealthRequest\"@\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x15\n" +
	"\x13CapabilitiesRequest\":\n" +
	"\x14CapabilitiesResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities2\xfe\x03\n" +
	"\x10CredentialLoader\x12F\n" +
	"\aResolve\x12\x1c.connector.v1.ResolveRequest\x1a\x1d.connector.v1.ResolveResponse\x12=\n" +
	"\x04List\x12\x19.connector.v1.ListRequest\x1a\x1a.connector.v1.ListResponse\x12@\n" +
	"\x05Lease\x12\x1a.connector.v1.LeaseRequest\x1a\x1b.connector.v1.LeaseResponse\x12@\n" +
	"\x05Renew\x12\x1a.connector.v1.RenewRequest\x1a\x1b.connector.v1.RenewResponse\x12C\n" +
	"\x06Revoke\x12\x1b.connector.v1.RevokeRequest\x1a\x1c.connector.v1.RevokeResponse\x12C\n" +
	"\x06Health\x12\x1b.connector.v1.HealthRequest\x1a\x1c.connector.v1.HealthResponse\x12U\n" +
	"\fCapabilities\x12!.connector.v1.CapabilitiesRequest\x1a\".connector.v1.CapabilitiesResponseB.Z,github.com/arqtiqa/arqtos-sdk-go/connectorpbb\x06proto3"

var (
	file_credentialloader_proto_rawDescOnce sync.Once
	file_credentialloader_proto_rawDescData []byte
)

func file_credentialloader_proto_rawDescGZIP() []byte {
	file_credentialloader_proto_rawDescOnce.Do(func() {
		file_credentialloader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credentialloader_proto_rawDesc), len(file_credentialloader_proto_rawDesc)))
	})
	return file_credentialloader_proto_rawDescData
}

var file_credentialloader_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_credentialloader_proto_goTypes = []any{
	(*Ref)(nil),                  // 0: connector.v1.Ref
	(*Material)(nil),             // 1: connector.v1.Material
	(*Lease)(nil),                // 2: connector.v1.Lease
	(*ResolveRequest)(nil),       // 3: connector.v1.ResolveRequest
	(*ResolveResponse)(nil),      // 4: connector.v1.ResolveResponse
	(*ListRequest)(nil),          // 5: connector.v1.ListRequest
	(*ListResponse)(nil),         // 6: connector.v1.ListResponse
	(*LeaseRequest)(nil),         // 7: connector.v1.LeaseRequest
	(*LeaseResponse)(nil),        // 8: connector.v1.LeaseResponse
	(*RenewRequest)(nil),         // 9: connector.v1.RenewRequest
	(*RenewResponse)(nil),        // 10: connector.v1.RenewResponse
	(*RevokeRequest)(nil),        // 11: connector.v1.RevokeRequest
	(*RevokeResponse)(nil),       // 12: connector.v1.RevokeResponse
	(*HealthRequest)(nil),        // 13: connector.v1.HealthRequest
	(*HealthResponse)(nil),       // 14: connector.v1.HealthResponse
	(*CapabilitiesRequest)(nil),  // 15: connector.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 16: connector.v1.CapabilitiesResponse
}
var file_credentialloader_proto_depIdxs = []int32{
	0,  // 0: connector.v1.ResolveRequest.ref:type_name -> connector.v1.Ref
	1,  // 1: connector.v1.ResolveResponse.material:type_name -> connector.v1.Material
	0,  // 2: connector.v1.ListResponse.refs:type_name -> connector.v1.Ref
	0,  // 3: connector.v1.LeaseRequest.ref:type_name -> connector.v1.Ref
	1,  // 4: connector.v1.LeaseResponse.material:type_name -> connector.v1.Material
	2,  // 5: connector.v1.LeaseResponse.lease:type_name -> connector.v1.Lease
	2,  // 6: connector.v1.RenewRequest.lease:type_name -> connector.v1.Lease
	2,  // 7: connector.v1.RenewResponse.lease:type_name -> connector.v1.Lease
	2,  // 8: connector.v1.RevokeRequest.lease:type_name -> connector.v1.Lease
	3,  // 9: connector.v1.CredentialLoader.Resolve:input_type -> connector.v1.ResolveRequest
	5,  // 10: connector.v1.CredentialLoader.List:input_type -> connector.v1.ListRequest
	7,  // 11: connector.v1.CredentialLoader.Lease:input_type -> connector.v1.LeaseRequest
	9,  // 12: connector.v1.CredentialLoader.Renew:input_type -> connector.v1.RenewRequest
	11, // 13: connector.v1.CredentialLoader.Revoke:input_type -> connector.v1.RevokeRequest
	13, // 14: connector.v1.CredentialLoader.Health:input_type -> connector.v1.HealthRequest
	15, // 15: connector.v1.CredentialLoader.Capabilities:input_type -> connector.v1.CapabilitiesRequest
	4,  // 16: connector.v1.CredentialLoader.Resolve:output_type -> connector.v1.ResolveResponse
	6,  // 17: connector.v1.CredentialLoader.List:output_type -> connector.v1.ListResponse
	8,  // 18: connector.v1.CredentialLoader.Lease:output_type -> connector.v1.LeaseResponse
	10, // 19: connector.v1.CredentialLoader.Renew:output_type -> connector.v1.RenewResponse
	12, // 20: connector.v1.CredentialLoader.Revoke:output_type -> connector.v1.RevokeResponse
	14, // 21: connector.v1.CredentialLoader.Health:output_type -> connector.v1.HealthResponse
	16, // 22: connector.v1.CredentialLoader.Capabilities:output_type -> connector.v1.CapabilitiesResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_credentialloader_proto_init() }
func file_credentialloader_proto_init() {
	if File_credentialloader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credentialloader_proto_rawDesc), len(file_credentialloader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credentialloader_proto_goTypes,
		DependencyIndexes: file_credentialloader_proto_depIdxs,
		MessageInfos:      file_credentialloader_proto_msgTypes,
	}.Build()
	File_credentialloader_proto = out.File
	file_credentialloader_proto_goTypes = nil
	file_credentialloader_proto_depIdxs = nil
}
