// The Track-B wire contract for the arqtos CredentialLoader connector class.
//
// This file is the contract for provider authors who will never read the Go
// SDK — including authors writing in another language. Everything a host
// relies on is stated here, in this file, rather than only in the Go doc
// comments of the reference implementation. If the two ever disagree, this
// file is what the wire actually carries.
//
// # The one rule that matters most
//
// A credential that DID NOT RESOLVE must never reach a host looking like a
// credential whose value is empty. That conflation is the bug this whole
// contract exists to prevent: a signed-out secret backend typically prints
// NOTHING and exits 0, and a provider that forwards that faithfully as a
// success hands the host "" — which then authenticates with an empty
// password instead of failing.
//
// So on this wire, "I resolved nothing" and "I resolved a value that is
// genuinely empty" have DIFFERENT encodings, and the accidental encoding —
// whatever a provider naturally emits when it has nothing — always means
// "resolved nothing", which is the safe reading. See Material below.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: credentialloader.proto

package connectorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialLoader_Resolve_FullMethodName        = "/connector.v1.CredentialLoader/Resolve"
	CredentialLoader_List_FullMethodName           = "/connector.v1.CredentialLoader/List"
	CredentialLoader_Lease_FullMethodName          = "/connector.v1.CredentialLoader/Lease"
	CredentialLoader_Renew_FullMethodName          = "/connector.v1.CredentialLoader/Renew"
	CredentialLoader_Revoke_FullMethodName         = "/connector.v1.CredentialLoader/Revoke"
	CredentialLoader_Health_FullMethodName         = "/connector.v1.CredentialLoader/Health"
	CredentialLoader_Capabilities_FullMethodName   = "/connector.v1.CredentialLoader/Capabilities"
	CredentialLoader_ResolveBatch_FullMethodName   = "/connector.v1.CredentialLoader/ResolveBatch"
	CredentialLoader_BindAuth_FullMethodName       = "/connector.v1.CredentialLoader/BindAuth"
	CredentialLoader_AcquireBundle_FullMethodName  = "/connector.v1.CredentialLoader/AcquireBundle"
	CredentialLoader_AuthStatus_FullMethodName     = "/connector.v1.CredentialLoader/AuthStatus"
	CredentialLoader_RenewAuth_FullMethodName      = "/connector.v1.CredentialLoader/RenewAuth"
	CredentialLoader_Reauthenticate_FullMethodName = "/connector.v1.CredentialLoader/Reauthenticate"
)

// CredentialLoaderClient is the client API for CredentialLoader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CredentialLoader is the out-of-process (Track-B) service a provider serves
// and a host dials. It mirrors the credential.CredentialLoader Go interface
// 1:1.
//
// # Errors
//
// Every failure is a gRPC status error whose CODE carries the
// classification — a host acts on the code, never on the message text:
//
//	NOT_FOUND           the ref, scope or lease does not exist
//	PERMISSION_DENIED   no access, including a backend session not signed in
//	UNAVAILABLE         the backing store is transiently unreachable
//	UNIMPLEMENTED       this connector does not support the operation
//	INVALID_ARGUMENT    malformed ref, unknown lease id
//	DEADLINE_EXCEEDED   the operation timed out
//	RESOURCE_EXHAUSTED  the backend reported a quota or rate limit
//	INTERNAL            reserved for host-detected contract violations
//	UNKNOWN             the provider could not classify the failure
//
// Error MESSAGES cross the wire verbatim and may be logged by the host, so
// they MUST NOT contain secret material.
type CredentialLoaderClient interface {
	// Resolve resolves ONE reference. See Material for what an empty or absent
	// material means — getting that wrong is the failure this contract is
	// built around.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	// List enumerates references under a connector-defined scope. Refs only.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Lease resolves a dynamic, time-bounded secret and returns its lease.
	Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*LeaseResponse, error)
	// Renew extends a lease previously returned by Lease.
	Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error)
	// Revoke invalidates a lease early. Idempotent.
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
	// Health reports reachability of the backing store.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Capabilities lists what this connector supports.
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// ResolveBatch resolves many references in ONE backend call.
	//
	// It is OPTIONAL, and gated: implement it only if you also report
	// "batch_resolve" from Capabilities and declare it in your manifest. A
	// provider that does not support it returns UNIMPLEMENTED.
	//
	// A returned status error means the batch CALL failed. A per-reference
	// failure belongs in that reference's ResolveBatchResult.failure, so one
	// missing field does not discard everything fetched with it.
	ResolveBatch(ctx context.Context, in *ResolveBatchRequest, opts ...grpc.CallOption) (*ResolveBatchResponse, error)
	// BindAuth delivers the host's bootstrap key set over the authenticated
	// channel. It is OPTIONAL, and gated: implement it only if you also report
	// "bind_auth" from Capabilities and declare it in your manifest. A
	// provider that does not support it returns UNIMPLEMENTED. Old hosts that
	// never call it keep the released refs-only Auth map as documentation of
	// required names, not as a delivery path.
	BindAuth(ctx context.Context, in *BindAuthRequest, opts ...grpc.CallOption) (*BindAuthResponse, error)
	// AcquireBundle loads a finite enrolled grant in ONE logical acquisition.
	// It is OPTIONAL, and gated: implement it only if you also report
	// "grant_bundle" from Capabilities and declare it in your manifest. A
	// provider that does not support it returns UNIMPLEMENTED.
	//
	// Completeness zero (unspecified) is NOT ready. Old peers that omit the
	// field cannot claim a complete grant. A partial page, a duplicate
	// identity, or a key outside the enrolled containers is a failed
	// acquisition, not a ready bundle. This is not ResolveBatch: one
	// acquisition may contain several backend requests.
	AcquireBundle(ctx context.Context, in *AcquireBundleRequest, opts ...grpc.CallOption) (*AcquireBundleResponse, error)
	// AuthStatus reports the connector's own outward-auth lifetime using the
	// host's clock (`now_unix`). It is OPTIONAL, gated by reporting
	// "auth_lifecycle". This is not Lease: a static KV under an expiring
	// login token must not advertise "lease". kind must be "auth"; a
	// secret_lease handle is invalid. The connector MUST NOT renew as a
	// side effect of this RPC.
	AuthStatus(ctx context.Context, in *AuthStatusRequest, opts ...grpc.CallOption) (*AuthStatusResponse, error)
	// RenewAuth extends an AuthSession when Renewable is true. Expired or
	// wrong-kind handles fail explicitly. Host-driven: the connector must not
	// run a hidden renewal loop.
	RenewAuth(ctx context.Context, in *RenewAuthRequest, opts ...grpc.CallOption) (*RenewAuthResponse, error)
	// Reauthenticate replaces the outward-auth session using host-supplied
	// bootstrap material (same BindAuth payload). Worker process death is
	// not evidence that the backend revoked anything.
	Reauthenticate(ctx context.Context, in *ReauthenticateRequest, opts ...grpc.CallOption) (*ReauthenticateResponse, error)
}

type credentialLoaderClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialLoaderClient(cc grpc.ClientConnInterface) CredentialLoaderClient {
	return &credentialLoaderClient{cc}
}

func (c *credentialLoaderClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*LeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_Lease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_Renew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) ResolveBatch(ctx context.Context, in *ResolveBatchRequest, opts ...grpc.CallOption) (*ResolveBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveBatchResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_ResolveBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) BindAuth(ctx context.Context, in *BindAuthRequest, opts ...grpc.CallOption) (*BindAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindAuthResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_BindAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) AcquireBundle(ctx context.Context, in *AcquireBundleRequest, opts ...grpc.CallOption) (*AcquireBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireBundleResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_AcquireBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) AuthStatus(ctx context.Context, in *AuthStatusRequest, opts ...grpc.CallOption) (*AuthStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthStatusResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_AuthStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) RenewAuth(ctx context.Context, in *RenewAuthRequest, opts ...grpc.CallOption) (*RenewAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewAuthResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_RenewAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialLoaderClient) Reauthenticate(ctx context.Context, in *ReauthenticateRequest, opts ...grpc.CallOption) (*ReauthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReauthenticateResponse)
	err := c.cc.Invoke(ctx, CredentialLoader_Reauthenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialLoaderServer is the server API for CredentialLoader service.
// All implementations must embed UnimplementedCredentialLoaderServer
// for forward compatibility.
//
// CredentialLoader is the out-of-process (Track-B) service a provider serves
// and a host dials. It mirrors the credential.CredentialLoader Go interface
// 1:1.
//
// # Errors
//
// Every failure is a gRPC status error whose CODE carries the
// classification — a host acts on the code, never on the message text:
//
//	NOT_FOUND           the ref, scope or lease does not exist
//	PERMISSION_DENIED   no access, including a backend session not signed in
//	UNAVAILABLE         the backing store is transiently unreachable
//	UNIMPLEMENTED       this connector does not support the operation
//	INVALID_ARGUMENT    malformed ref, unknown lease id
//	DEADLINE_EXCEEDED   the operation timed out
//	RESOURCE_EXHAUSTED  the backend reported a quota or rate limit
//	INTERNAL            reserved for host-detected contract violations
//	UNKNOWN             the provider could not classify the failure
//
// Error MESSAGES cross the wire verbatim and may be logged by the host, so
// they MUST NOT contain secret material.
type CredentialLoaderServer interface {
	// Resolve resolves ONE reference. See Material for what an empty or absent
	// material means — getting that wrong is the failure this contract is
	// built around.
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	// List enumerates references under a connector-defined scope. Refs only.
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Lease resolves a dynamic, time-bounded secret and returns its lease.
	Lease(context.Context, *LeaseRequest) (*LeaseResponse, error)
	// Renew extends a lease previously returned by Lease.
	Renew(context.Context, *RenewRequest) (*RenewResponse, error)
	// Revoke invalidates a lease early. Idempotent.
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
	// Health reports reachability of the backing store.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Capabilities lists what this connector supports.
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	// ResolveBatch resolves many references in ONE backend call.
	//
	// It is OPTIONAL, and gated: implement it only if you also report
	// "batch_resolve" from Capabilities and declare it in your manifest. A
	// provider that does not support it returns UNIMPLEMENTED.
	//
	// A returned status error means the batch CALL failed. A per-reference
	// failure belongs in that reference's ResolveBatchResult.failure, so one
	// missing field does not discard everything fetched with it.
	ResolveBatch(context.Context, *ResolveBatchRequest) (*ResolveBatchResponse, error)
	// BindAuth delivers the host's bootstrap key set over the authenticated
	// channel. It is OPTIONAL, and gated: implement it only if you also report
	// "bind_auth" from Capabilities and declare it in your manifest. A
	// provider that does not support it returns UNIMPLEMENTED. Old hosts that
	// never call it keep the released refs-only Auth map as documentation of
	// required names, not as a delivery path.
	BindAuth(context.Context, *BindAuthRequest) (*BindAuthResponse, error)
	// AcquireBundle loads a finite enrolled grant in ONE logical acquisition.
	// It is OPTIONAL, and gated: implement it only if you also report
	// "grant_bundle" from Capabilities and declare it in your manifest. A
	// provider that does not support it returns UNIMPLEMENTED.
	//
	// Completeness zero (unspecified) is NOT ready. Old peers that omit the
	// field cannot claim a complete grant. A partial page, a duplicate
	// identity, or a key outside the enrolled containers is a failed
	// acquisition, not a ready bundle. This is not ResolveBatch: one
	// acquisition may contain several backend requests.
	AcquireBundle(context.Context, *AcquireBundleRequest) (*AcquireBundleResponse, error)
	// AuthStatus reports the connector's own outward-auth lifetime using the
	// host's clock (`now_unix`). It is OPTIONAL, gated by reporting
	// "auth_lifecycle". This is not Lease: a static KV under an expiring
	// login token must not advertise "lease". kind must be "auth"; a
	// secret_lease handle is invalid. The connector MUST NOT renew as a
	// side effect of this RPC.
	AuthStatus(context.Context, *AuthStatusRequest) (*AuthStatusResponse, error)
	// RenewAuth extends an AuthSession when Renewable is true. Expired or
	// wrong-kind handles fail explicitly. Host-driven: the connector must not
	// run a hidden renewal loop.
	RenewAuth(context.Context, *RenewAuthRequest) (*RenewAuthResponse, error)
	// Reauthenticate replaces the outward-auth session using host-supplied
	// bootstrap material (same BindAuth payload). Worker process death is
	// not evidence that the backend revoked anything.
	Reauthenticate(context.Context, *ReauthenticateRequest) (*ReauthenticateResponse, error)
	mustEmbedUnimplementedCredentialLoaderServer()
}

// UnimplementedCredentialLoaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialLoaderServer struct{}

func (UnimplementedCredentialLoaderServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedCredentialLoaderServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCredentialLoaderServer) Lease(context.Context, *LeaseRequest) (*LeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lease not implemented")
}
func (UnimplementedCredentialLoaderServer) Renew(context.Context, *RenewRequest) (*RenewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Renew not implemented")
}
func (UnimplementedCredentialLoaderServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedCredentialLoaderServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCredentialLoaderServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedCredentialLoaderServer) ResolveBatch(context.Context, *ResolveBatchRequest) (*ResolveBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveBatch not implemented")
}
func (UnimplementedCredentialLoaderServer) BindAuth(context.Context, *BindAuthRequest) (*BindAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindAuth not implemented")
}
func (UnimplementedCredentialLoaderServer) AcquireBundle(context.Context, *AcquireBundleRequest) (*AcquireBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireBundle not implemented")
}
func (UnimplementedCredentialLoaderServer) AuthStatus(context.Context, *AuthStatusRequest) (*AuthStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthStatus not implemented")
}
func (UnimplementedCredentialLoaderServer) RenewAuth(context.Context, *RenewAuthRequest) (*RenewAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewAuth not implemented")
}
func (UnimplementedCredentialLoaderServer) Reauthenticate(context.Context, *ReauthenticateRequest) (*ReauthenticateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reauthenticate not implemented")
}
func (UnimplementedCredentialLoaderServer) mustEmbedUnimplementedCredentialLoaderServer() {}
func (UnimplementedCredentialLoaderServer) testEmbeddedByValue()                          {}

// UnsafeCredentialLoaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialLoaderServer will
// result in compilation errors.
type UnsafeCredentialLoaderServer interface {
	mustEmbedUnimplementedCredentialLoaderServer()
}

func RegisterCredentialLoaderServer(s grpc.ServiceRegistrar, srv CredentialLoaderServer) {
	// If the following call panics, it indicates UnimplementedCredentialLoaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialLoader_ServiceDesc, srv)
}

func _CredentialLoader_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_Lease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).Lease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_Lease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).Lease(ctx, req.(*LeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_Renew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).Renew(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_ResolveBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).ResolveBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_ResolveBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).ResolveBatch(ctx, req.(*ResolveBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_BindAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).BindAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_BindAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).BindAuth(ctx, req.(*BindAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_AcquireBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).AcquireBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_AcquireBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).AcquireBundle(ctx, req.(*AcquireBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_AuthStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).AuthStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_AuthStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).AuthStatus(ctx, req.(*AuthStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_RenewAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).RenewAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_RenewAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).RenewAuth(ctx, req.(*RenewAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialLoader_Reauthenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReauthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialLoaderServer).Reauthenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialLoader_Reauthenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialLoaderServer).Reauthenticate(ctx, req.(*ReauthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialLoader_ServiceDesc is the grpc.ServiceDesc for CredentialLoader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialLoader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connector.v1.CredentialLoader",
	HandlerType: (*CredentialLoaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _CredentialLoader_Resolve_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CredentialLoader_List_Handler,
		},
		{
			MethodName: "Lease",
			Handler:    _CredentialLoader_Lease_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _CredentialLoader_Renew_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _CredentialLoader_Revoke_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CredentialLoader_Health_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _CredentialLoader_Capabilities_Handler,
		},
		{
			MethodName: "ResolveBatch",
			Handler:    _CredentialLoader_ResolveBatch_Handler,
		},
		{
			MethodName: "BindAuth",
			Handler:    _CredentialLoader_BindAuth_Handler,
		},
		{
			MethodName: "AcquireBundle",
			Handler:    _CredentialLoader_AcquireBundle_Handler,
		},
		{
			MethodName: "AuthStatus",
			Handler:    _CredentialLoader_AuthStatus_Handler,
		},
		{
			MethodName: "RenewAuth",
			Handler:    _CredentialLoader_RenewAuth_Handler,
		},
		{
			MethodName: "Reauthenticate",
			Handler:    _CredentialLoader_Reauthenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "credentialloader.proto",
}
