// The Track-B wire contract for the arqtos CredentialLoader connector class.
//
// This file is the contract for provider authors who will never read the Go
// SDK — including authors writing in another language. Everything a host
// relies on is stated here, in this file, rather than only in the Go doc
// comments of the reference implementation. If the two ever disagree, this
// file is what the wire actually carries.
//
// # The one rule that matters most
//
// A credential that DID NOT RESOLVE must never reach a host looking like a
// credential whose value is empty. That conflation is the bug this whole
// contract exists to prevent: a signed-out secret backend typically prints
// NOTHING and exits 0, and a provider that forwards that faithfully as a
// success hands the host "" — which then authenticates with an empty
// password instead of failing.
//
// So on this wire, "I resolved nothing" and "I resolved a value that is
// genuinely empty" have DIFFERENT encodings, and the accidental encoding —
// whatever a provider naturally emits when it has nothing — always means
// "resolved nothing", which is the safe reading. See Material below.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: credentialloader.proto

package connectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BundleCompleteness int32

const (
	BundleCompleteness_BUNDLE_COMPLETENESS_UNSPECIFIED BundleCompleteness = 0
	BundleCompleteness_BUNDLE_COMPLETENESS_COMPLETE    BundleCompleteness = 1
	BundleCompleteness_BUNDLE_COMPLETENESS_INCOMPLETE  BundleCompleteness = 2
)

// Enum value maps for BundleCompleteness.
var (
	BundleCompleteness_name = map[int32]string{
		0: "BUNDLE_COMPLETENESS_UNSPECIFIED",
		1: "BUNDLE_COMPLETENESS_COMPLETE",
		2: "BUNDLE_COMPLETENESS_INCOMPLETE",
	}
	BundleCompleteness_value = map[string]int32{
		"BUNDLE_COMPLETENESS_UNSPECIFIED": 0,
		"BUNDLE_COMPLETENESS_COMPLETE":    1,
		"BUNDLE_COMPLETENESS_INCOMPLETE":  2,
	}
)

func (x BundleCompleteness) Enum() *BundleCompleteness {
	p := new(BundleCompleteness)
	*p = x
	return p
}

func (x BundleCompleteness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BundleCompleteness) Descriptor() protoreflect.EnumDescriptor {
	return file_credentialloader_proto_enumTypes[0].Descriptor()
}

func (BundleCompleteness) Type() protoreflect.EnumType {
	return &file_credentialloader_proto_enumTypes[0]
}

func (x BundleCompleteness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BundleCompleteness.Descriptor instead.
func (BundleCompleteness) EnumDescriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{0}
}

// Ref is an op://<vault>/<item>/<field> secret reference: the ADDRESS of a
// secret, never the secret itself. All three segments are required and
// non-empty; a host sends only refs, and a provider returns only the material
// for the ref it was asked about.
type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vault         string                 `protobuf:"bytes,1,opt,name=vault,proto3" json:"vault,omitempty"`
	Item          string                 `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_credentialloader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{0}
}

func (x *Ref) GetVault() string {
	if x != nil {
		return x.Vault
	}
	return ""
}

func (x *Ref) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Ref) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

// Material is resolved secret material, and the presence rules below are the
// contract's load-bearing part.
//
// Read the three cases as a WHOLE MESSAGE, not as a bytes field:
//
//  1. NO Material message at all (the containing field is unset)
//     -> nothing was resolved. The host treats this as a failure and refuses
//     to produce a readable credential from it.
//
//  2. Material with `value` non-empty
//     -> that is the secret. `empty_by_assertion` is ignored here; bytes
//     present always mean a resolved value.
//
//  3. Material with no `value` bytes AND `empty_by_assertion = true`
//     -> the provider ASSERTS the stored secret is genuinely, intentionally
//     empty. The host produces a readable credential of length zero.
//
//  4. Material with no `value` bytes and NO `empty_by_assertion`
//     -> nothing was resolved. Identical to case 1. This is deliberate: it
//     is the encoding a provider produces by accident (an unset struct,
//     a default-constructed message, a "" it forwarded from a backend),
//     and the accidental encoding must have the SAFE meaning.
//
// Note that proto3 does not put a zero-length `bytes` field on the wire at
// all, so cases 3 and 4 differ ONLY by the boolean. That is exactly why the
// boolean exists: without it, a conformant "deliberately empty" and a rogue
// "I got nothing" are byte-identical and the host cannot tell them apart.
type Material struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The secret bytes. Empty or absent means NO VALUE unless
	// empty_by_assertion is set — see the message comment above.
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Set this ONLY to assert "this credential is deliberately, genuinely
	// empty". Set it only if your backend can distinguish a STORED EMPTY VALUE
	// from an unauthenticated, missing, or failed read. If it cannot make that
	// distinction, you have a failure on your hands, not an empty secret:
	// return a gRPC status error instead (see the error mapping below).
	//
	// Absent bytes WITHOUT this flag means nothing was resolved, and the host
	// refuses it — naming your connector in the fault it reports.
	EmptyByAssertion bool `protobuf:"varint,2,opt,name=empty_by_assertion,json=emptyByAssertion,proto3" json:"empty_by_assertion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_credentialloader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{1}
}

func (x *Material) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Material) GetEmptyByAssertion() bool {
	if x != nil {
		return x.EmptyByAssertion
	}
	return false
}

// Lease describes a dynamic, time-bounded secret's validity window.
type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Renewable     bool                   `protobuf:"varint,4,opt,name=renewable,proto3" json:"renewable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_credentialloader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{2}
}

func (x *Lease) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lease) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *Lease) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Lease) GetRenewable() bool {
	if x != nil {
		return x.Renewable
	}
	return false
}

// Failure is ONE reference's typed failure inside a batch response.
//
// A whole-call failure is a gRPC status error on the RPC itself. This message
// exists because a batch RPC that SUCCEEDED can still carry a per-reference
// failure, and one missing field must not discard the other ninety-nine
// values fetched with it.
//
// `code` is a google.rpc.Code / gRPC status code number, carrying the same
// classification a single Resolve would return as a status error; `message`
// is the human-readable detail. A host maps the code back into its closed
// error vocabulary, so it acts on the classification and never on the text.
//
// MUST NOT contain secret material: unlike Material, failure text crosses the
// wire verbatim and a host may write it to an audit log.
type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_credentialloader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{3}
}

func (x *Failure) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_credentialloader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

// ResolveResponse carries the resolved material, subject to Material's
// presence rules. An UNSET material field means nothing was resolved; it is
// the correct way to say so alongside a non-error response, though returning
// a gRPC status error is better still because it also says WHY.
type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_credentialloader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveResponse) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_credentialloader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// ListResponse returns REFERENCES ONLY. A List must never resolve material
// for the entries it enumerates.
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*Ref                 `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_credentialloader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetRefs() []*Ref {
	if x != nil {
		return x.Refs
	}
	return nil
}

type LeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_credentialloader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{8}
}

func (x *LeaseRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

// LeaseResponse carries the leased material — same Material presence rules as
// ResolveResponse — plus the lease describing its validity window.
type LeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	Lease         *Lease                 `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseResponse) Reset() {
	*x = LeaseResponse{}
	mi := &file_credentialloader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseResponse) ProtoMessage() {}

func (x *LeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseResponse.ProtoReflect.Descriptor instead.
func (*LeaseResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{9}
}

func (x *LeaseResponse) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *LeaseResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_credentialloader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{10}
}

func (x *RenewRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_credentialloader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{11}
}

func (x *RenewResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_credentialloader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_credentialloader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{13}
}

// BindAuthRequest carries host-supplied bootstrap material for the
// connector's own outward authentication. It is not a secret the host is
// asking to resolve — those stay refs-only. Token and two-key profiles use
// this same message: the required names are the profile, not a second RPC.
//
// Keys MUST NOT be logged, written to argv, copied into the process
// environment, or persisted. Empty `value` bytes are still a present key.
type BindAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*BootstrapEntry      `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindAuthRequest) Reset() {
	*x = BindAuthRequest{}
	mi := &file_credentialloader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindAuthRequest) ProtoMessage() {}

func (x *BindAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindAuthRequest.ProtoReflect.Descriptor instead.
func (*BindAuthRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{14}
}

func (x *BindAuthRequest) GetKeys() []*BootstrapEntry {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BootstrapEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapEntry) Reset() {
	*x = BootstrapEntry{}
	mi := &file_credentialloader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapEntry) ProtoMessage() {}

func (x *BootstrapEntry) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapEntry.ProtoReflect.Descriptor instead.
func (*BootstrapEntry) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{15}
}

func (x *BootstrapEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BootstrapEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BindAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindAuthResponse) Reset() {
	*x = BindAuthResponse{}
	mi := &file_credentialloader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindAuthResponse) ProtoMessage() {}

func (x *BindAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindAuthResponse.ProtoReflect.Descriptor instead.
func (*BindAuthResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{16}
}

// ResolveBatchRequest asks for many references in ONE call.
type ResolveBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refs          []*Ref                 `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveBatchRequest) Reset() {
	*x = ResolveBatchRequest{}
	mi := &file_credentialloader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBatchRequest) ProtoMessage() {}

func (x *ResolveBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBatchRequest.ProtoReflect.Descriptor instead.
func (*ResolveBatchRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{17}
}

func (x *ResolveBatchRequest) GetRefs() []*Ref {
	if x != nil {
		return x.Refs
	}
	return nil
}

// ResolveBatchResult is ONE requested reference's outcome: EXACTLY ONE of a
// resolved material or a typed failure, never both and never neither.
//
//   - `ref` echoes the reference this result answers, so a host can attribute
//     a result without relying on position alone. It is required.
//   - `material` follows Material's presence rules exactly, including
//     `empty_by_assertion`. Absent-and-unasserted means nothing was resolved.
//   - `failure` is this reference's typed failure.
//
// A result carrying NEITHER — no failure, and no material or an unasserted
// empty one — is a contract violation the host reports against your
// connector by name. It is not read as an empty credential.
type ResolveBatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Material      *Material              `protobuf:"bytes,2,opt,name=material,proto3" json:"material,omitempty"`
	Failure       *Failure               `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveBatchResult) Reset() {
	*x = ResolveBatchResult{}
	mi := &file_credentialloader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBatchResult) ProtoMessage() {}

func (x *ResolveBatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBatchResult.ProtoReflect.Descriptor instead.
func (*ResolveBatchResult) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{18}
}

func (x *ResolveBatchResult) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ResolveBatchResult) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

func (x *ResolveBatchResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

// ResolveBatchResponse returns EXACTLY ONE result per requested reference, IN
// THE REQUESTED ORDER. A host verifies both, and refuses the whole batch if
// either is wrong: it cannot attribute mismatched results to the references
// it asked about, and guessing the correspondence is how the wrong secret
// reaches the wrong caller.
type ResolveBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ResolveBatchResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveBatchResponse) Reset() {
	*x = ResolveBatchResponse{}
	mi := &file_credentialloader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveBatchResponse) ProtoMessage() {}

func (x *ResolveBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveBatchResponse.ProtoReflect.Descriptor instead.
func (*ResolveBatchResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{19}
}

func (x *ResolveBatchResponse) GetResults() []*ResolveBatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type AuthSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Renewable     bool                   `protobuf:"varint,4,opt,name=renewable,proto3" json:"renewable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSession) Reset() {
	*x = AuthSession{}
	mi := &file_credentialloader_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSession) ProtoMessage() {}

func (x *AuthSession) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSession.ProtoReflect.Descriptor instead.
func (*AuthSession) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{20}
}

func (x *AuthSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthSession) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AuthSession) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *AuthSession) GetRenewable() bool {
	if x != nil {
		return x.Renewable
	}
	return false
}

type AuthStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NowUnix       int64                  `protobuf:"varint,1,opt,name=now_unix,json=nowUnix,proto3" json:"now_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthStatusRequest) Reset() {
	*x = AuthStatusRequest{}
	mi := &file_credentialloader_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthStatusRequest) ProtoMessage() {}

func (x *AuthStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthStatusRequest.ProtoReflect.Descriptor instead.
func (*AuthStatusRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{21}
}

func (x *AuthStatusRequest) GetNowUnix() int64 {
	if x != nil {
		return x.NowUnix
	}
	return 0
}

type AuthStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthStatusResponse) Reset() {
	*x = AuthStatusResponse{}
	mi := &file_credentialloader_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthStatusResponse) ProtoMessage() {}

func (x *AuthStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthStatusResponse.ProtoReflect.Descriptor instead.
func (*AuthStatusResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{22}
}

func (x *AuthStatusResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type RenewAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	NowUnix       int64                  `protobuf:"varint,2,opt,name=now_unix,json=nowUnix,proto3" json:"now_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewAuthRequest) Reset() {
	*x = RenewAuthRequest{}
	mi := &file_credentialloader_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewAuthRequest) ProtoMessage() {}

func (x *RenewAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewAuthRequest.ProtoReflect.Descriptor instead.
func (*RenewAuthRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{23}
}

func (x *RenewAuthRequest) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RenewAuthRequest) GetNowUnix() int64 {
	if x != nil {
		return x.NowUnix
	}
	return 0
}

type RenewAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewAuthResponse) Reset() {
	*x = RenewAuthResponse{}
	mi := &file_credentialloader_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewAuthResponse) ProtoMessage() {}

func (x *RenewAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewAuthResponse.ProtoReflect.Descriptor instead.
func (*RenewAuthResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{24}
}

func (x *RenewAuthResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type ReauthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bootstrap     *BindAuthRequest       `protobuf:"bytes,1,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	NowUnix       int64                  `protobuf:"varint,2,opt,name=now_unix,json=nowUnix,proto3" json:"now_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReauthenticateRequest) Reset() {
	*x = ReauthenticateRequest{}
	mi := &file_credentialloader_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReauthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReauthenticateRequest) ProtoMessage() {}

func (x *ReauthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReauthenticateRequest.ProtoReflect.Descriptor instead.
func (*ReauthenticateRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{25}
}

func (x *ReauthenticateRequest) GetBootstrap() *BindAuthRequest {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

func (x *ReauthenticateRequest) GetNowUnix() int64 {
	if x != nil {
		return x.NowUnix
	}
	return 0
}

type ReauthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *AuthSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReauthenticateResponse) Reset() {
	*x = ReauthenticateResponse{}
	mi := &file_credentialloader_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReauthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReauthenticateResponse) ProtoMessage() {}

func (x *ReauthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReauthenticateResponse.ProtoReflect.Descriptor instead.
func (*ReauthenticateResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{26}
}

func (x *ReauthenticateResponse) GetSession() *AuthSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type GrantInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Containers    []string               `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	Keys          []*Ref                 `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	Coverage      string                 `protobuf:"bytes,4,opt,name=coverage,proto3" json:"coverage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantInventory) Reset() {
	*x = GrantInventory{}
	mi := &file_credentialloader_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantInventory) ProtoMessage() {}

func (x *GrantInventory) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantInventory.ProtoReflect.Descriptor instead.
func (*GrantInventory) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{27}
}

func (x *GrantInventory) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *GrantInventory) GetContainers() []string {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *GrantInventory) GetKeys() []*Ref {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GrantInventory) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

type BundleEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *Ref                   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Material      *Material              `protobuf:"bytes,2,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleEntry) Reset() {
	*x = BundleEntry{}
	mi := &file_credentialloader_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleEntry) ProtoMessage() {}

func (x *BundleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleEntry.ProtoReflect.Descriptor instead.
func (*BundleEntry) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{28}
}

func (x *BundleEntry) GetIdentity() *Ref {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *BundleEntry) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type AcquireBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *GrantInventory        `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireBundleRequest) Reset() {
	*x = AcquireBundleRequest{}
	mi := &file_credentialloader_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireBundleRequest) ProtoMessage() {}

func (x *AcquireBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireBundleRequest.ProtoReflect.Descriptor instead.
func (*AcquireBundleRequest) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{29}
}

func (x *AcquireBundleRequest) GetInventory() *GrantInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type AcquireBundleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Generation     string                 `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	AcquiredAtUnix int64                  `protobuf:"varint,3,opt,name=acquired_at_unix,json=acquiredAtUnix,proto3" json:"acquired_at_unix,omitempty"`
	Coverage       string                 `protobuf:"bytes,4,opt,name=coverage,proto3" json:"coverage,omitempty"`
	Entries        []*BundleEntry         `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	Completeness   BundleCompleteness     `protobuf:"varint,6,opt,name=completeness,proto3,enum=connector.v1.BundleCompleteness" json:"completeness,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcquireBundleResponse) Reset() {
	*x = AcquireBundleResponse{}
	mi := &file_credentialloader_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireBundleResponse) ProtoMessage() {}

func (x *AcquireBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credentialloader_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireBundleResponse.ProtoReflect.Descriptor instead.
func (*AcquireBundleResponse) Descriptor() ([]byte, []int) {
	return file_credentialloader_proto_rawDescGZIP(), []int{30}
}

func (x *AcquireBundleResponse) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *AcquireBundleResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AcquireBundleResponse) GetAcquiredAtUnix() int64 {
	if x != nil {
		return x.AcquiredAtUnix
	}
	return 0
}

func (x *AcquireBundleResponse) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

func (x *AcquireBundleResponse) GetEntries() []*BundleEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AcquireBundleResponse) GetCompleteness() BundleCompleteness {
	if x != nil {
		return x.Completeness
	}
	return BundleCompleteness_BUNDLE_COMPLETENESS_UNSPECIFIED
}

var File_credentialloader_proto protoreflect.FileDescriptor

const file_credentialloader_proto_rawDesc = "" +
	"\n" +
	"\x16credentialloader.proto\x12\fconnector.v1\x1a\x0fconnector.proto\"E\n" +
	"\x03Ref\x12\x14\n" +
	"\x05vault\x18\x01 \x01(\tR\x05vault\x12\x12\n" +
	"\x04item\x18\x02 \x01(\tR\x04item\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\"N\n" +
	"\bMaterial\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12,\n" +
	"\x12empty_by_assertion\x18\x02 \x01(\bR\x10emptyByAssertion\"~\n" +
	"\x05Lease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12\x1c\n" +
	"\trenewable\x18\x04 \x01(\bR\trenewable\"7\n" +
	"\aFailure\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x0eResolveRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.connector.v1.RefR\x03ref\"E\n" +
	"\x0fResolveResponse\x122\n" +
	"\bmaterial\x18\x01 \x01(\v2\x16.connector.v1.MaterialR\bmaterial\"#\n" +
	"\vListRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"5\n" +
	"\fListResponse\x12%\n" +
	"\x04refs\x18\x01 \x03(\v2\x11.connector.v1.RefR\x04refs\"3\n" +
	"\fLeaseRequest\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.connector.v1.RefR\x03ref\"n\n" +
	"\rLeaseResponse\x122\n" +
	"\bmaterial\x18\x01 \x01(\v2\x16.connector.v1.MaterialR\bmaterial\x12)\n" +
	"\x05lease\x18\x02 \x01(\v2\x13.connector.v1.LeaseR\x05lease\"9\n" +
	"\fRenewRequest\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.connector.v1.LeaseR\x05lease\":\n" +
	"\rRenewResponse\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.connector.v1.LeaseR\x05lease\":\n" +
	"\rRevokeRequest\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.connector.v1.LeaseR\x05lease\"\x10\n" +
	"\x0eRevokeResponse\"C\n" +
	"\x0fBindAuthRequest\x120\n" +
	"\x04keys\x18\x01 \x03(\v2\x1c.connector.v1.BootstrapEntryR\x04keys\":\n" +
	"\x0eBootstrapEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x12\n" +
	"\x10BindAuthResponse\"<\n" +
	"\x13ResolveBatchRequest\x12%\n" +
	"\x04refs\x18\x01 \x03(\v2\x11.connector.v1.RefR\x04refs\"\x9e\x01\n" +
	"\x12ResolveBatchResult\x12#\n" +
	"\x03ref\x18\x01 \x01(\v2\x11.connector.v1.RefR\x03ref\x122\n" +
	"\bmaterial\x18\x02 \x01(\v2\x16.connector.v1.MaterialR\bmaterial\x12/\n" +
	"\afailure\x18\x03 \x01(\v2\x15.connector.v1.FailureR\afailure\"R\n" +
	"\x14ResolveBatchResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .connector.v1.ResolveBatchResultR\aresults\"w\n" +
	"\vAuthSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12\x1c\n" +
	"\trenewable\x18\x04 \x01(\bR\trenewable\".\n" +
	"\x11AuthStatusRequest\x12\x19\n" +
	"\bnow_unix\x18\x01 \x01(\x03R\anowUnix\"I\n" +
	"\x12AuthStatusResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.connector.v1.AuthSessionR\asession\"b\n" +
	"\x10RenewAuthRequest\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.connector.v1.AuthSessionR\asession\x12\x19\n" +
	"\bnow_unix\x18\x02 \x01(\x03R\anowUnix\"H\n" +
	"\x11RenewAuthResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.connector.v1.AuthSessionR\asession\"o\n" +
	"\x15ReauthenticateRequest\x12;\n" +
	"\tbootstrap\x18\x01 \x01(\v2\x1d.connector.v1.BindAuthRequestR\tbootstrap\x12\x19\n" +
	"\bnow_unix\x18\x02 \x01(\x03R\anowUnix\"M\n" +
	"\x16ReauthenticateResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.connector.v1.AuthSessionR\asession\"\x91\x01\n" +
	"\x0eGrantInventory\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12\x1e\n" +
	"\n" +
	"containers\x18\x02 \x03(\tR\n" +
	"containers\x12%\n" +
	"\x04keys\x18\x03 \x03(\v2\x11.connector.v1.RefR\x04keys\x12\x1a\n" +
	"\bcoverage\x18\x04 \x01(\tR\bcoverage\"p\n" +
	"\vBundleEntry\x12-\n" +
	"\bidentity\x18\x01 \x01(\v2\x11.connector.v1.RefR\bidentity\x122\n" +
	"\bmaterial\x18\x02 \x01(\v2\x16.connector.v1.MaterialR\bmaterial\"R\n" +
	"\x14AcquireBundleRequest\x12:\n" +
	"\tinventory\x18\x01 \x01(\v2\x1c.connector.v1.GrantInventoryR\tinventory\"\x90\x02\n" +
	"\x15AcquireBundleResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\tR\n" +
	"generation\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12(\n" +
	"\x10acquired_at_unix\x18\x03 \x01(\x03R\x0eacquiredAtUnix\x12\x1a\n" +
	"\bcoverage\x18\x04 \x01(\tR\bcoverage\x123\n" +
	"\aentries\x18\x05 \x03(\v2\x19.connector.v1.BundleEntryR\aentries\x12D\n" +
	"\fcompleteness\x18\x06 \x01(\x0e2 .connector.v1.BundleCompletenessR\fcompleteness*\x7f\n" +
	"\x12BundleCompleteness\x12#\n" +
	"\x1fBUNDLE_COMPLETENESS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cBUNDLE_COMPLETENESS_COMPLETE\x10\x01\x12\"\n" +
	"\x1eBUNDLE_COMPLETENESS_INCOMPLETE\x10\x022\xf6\a\n" +
	"\x10CredentialLoader\x12F\n" +
	"\aResolve\x12\x1c.connector.v1.ResolveRequest\x1a\x1d.connector.v1.ResolveResponse\x12=\n" +
	"\x04List\x12\x19.connector.v1.ListRequest\x1a\x1a.connector.v1.ListResponse\x12@\n" +
	"\x05Lease\x12\x1a.connector.v1.LeaseRequest\x1a\x1b.connector.v1.LeaseResponse\x12@\n" +
	"\x05Renew\x12\x1a.connector.v1.RenewRequest\x1a\x1b.connector.v1.RenewResponse\x12C\n" +
	"\x06Revoke\x12\x1b.connector.v1.RevokeRequest\x1a\x1c.connector.v1.RevokeResponse\x12C\n" +
	"\x06Health\x12\x1b.connector.v1.HealthRequest\x1a\x1c.connector.v1.HealthResponse\x12U\n" +
	"\fCapabilities\x12!.connector.v1.CapabilitiesRequest\x1a\".connector.v1.CapabilitiesResponse\x12U\n" +
	"\fResolveBatch\x12!.connector.v1.ResolveBatchRequest\x1a\".connector.v1.ResolveBatchResponse\x12I\n" +
	"\bBindAuth\x12\x1d.connector.v1.BindAuthRequest\x1a\x1e.connector.v1.BindAuthResponse\x12X\n" +
	"\rAcquireBundle\x12\".connector.v1.AcquireBundleRequest\x1a#.connector.v1.AcquireBundleResponse\x12O\n" +
	"\n" +
	"AuthStatus\x12\x1f.connector.v1.AuthStatusRequest\x1a .connector.v1.AuthStatusResponse\x12L\n" +
	"\tRenewAuth\x12\x1e.connector.v1.RenewAuthRequest\x1a\x1f.connector.v1.RenewAuthResponse\x12[\n" +
	"\x0eReauthenticate\x12#.connector.v1.ReauthenticateRequest\x1a$.connector.v1.ReauthenticateResponseB.Z,github.com/arqtiqa/arqtos-sdk-go/connectorpbb\x06proto3"

var (
	file_credentialloader_proto_rawDescOnce sync.Once
	file_credentialloader_proto_rawDescData []byte
)

func file_credentialloader_proto_rawDescGZIP() []byte {
	file_credentialloader_proto_rawDescOnce.Do(func() {
		file_credentialloader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credentialloader_proto_rawDesc), len(file_credentialloader_proto_rawDesc)))
	})
	return file_credentialloader_proto_rawDescData
}

var file_credentialloader_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_credentialloader_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_credentialloader_proto_goTypes = []any{
	(BundleCompleteness)(0),        // 0: connector.v1.BundleCompleteness
	(*Ref)(nil),                    // 1: connector.v1.Ref
	(*Material)(nil),               // 2: connector.v1.Material
	(*Lease)(nil),                  // 3: connector.v1.Lease
	(*Failure)(nil),                // 4: connector.v1.Failure
	(*ResolveRequest)(nil),         // 5: connector.v1.ResolveRequest
	(*ResolveResponse)(nil),        // 6: connector.v1.ResolveResponse
	(*ListRequest)(nil),            // 7: connector.v1.ListRequest
	(*ListResponse)(nil),           // 8: connector.v1.ListResponse
	(*LeaseRequest)(nil),           // 9: connector.v1.LeaseRequest
	(*LeaseResponse)(nil),          // 10: connector.v1.LeaseResponse
	(*RenewRequest)(nil),           // 11: connector.v1.RenewRequest
	(*RenewResponse)(nil),          // 12: connector.v1.RenewResponse
	(*RevokeRequest)(nil),          // 13: connector.v1.RevokeRequest
	(*RevokeResponse)(nil),         // 14: connector.v1.RevokeResponse
	(*BindAuthRequest)(nil),        // 15: connector.v1.BindAuthRequest
	(*BootstrapEntry)(nil),         // 16: connector.v1.BootstrapEntry
	(*BindAuthResponse)(nil),       // 17: connector.v1.BindAuthResponse
	(*ResolveBatchRequest)(nil),    // 18: connector.v1.ResolveBatchRequest
	(*ResolveBatchResult)(nil),     // 19: connector.v1.ResolveBatchResult
	(*ResolveBatchResponse)(nil),   // 20: connector.v1.ResolveBatchResponse
	(*AuthSession)(nil),            // 21: connector.v1.AuthSession
	(*AuthStatusRequest)(nil),      // 22: connector.v1.AuthStatusRequest
	(*AuthStatusResponse)(nil),     // 23: connector.v1.AuthStatusResponse
	(*RenewAuthRequest)(nil),       // 24: connector.v1.RenewAuthRequest
	(*RenewAuthResponse)(nil),      // 25: connector.v1.RenewAuthResponse
	(*ReauthenticateRequest)(nil),  // 26: connector.v1.ReauthenticateRequest
	(*ReauthenticateResponse)(nil), // 27: connector.v1.ReauthenticateResponse
	(*GrantInventory)(nil),         // 28: connector.v1.GrantInventory
	(*BundleEntry)(nil),            // 29: connector.v1.BundleEntry
	(*AcquireBundleRequest)(nil),   // 30: connector.v1.AcquireBundleRequest
	(*AcquireBundleResponse)(nil),  // 31: connector.v1.AcquireBundleResponse
	(*HealthRequest)(nil),          // 32: connector.v1.HealthRequest
	(*CapabilitiesRequest)(nil),    // 33: connector.v1.CapabilitiesRequest
	(*HealthResponse)(nil),         // 34: connector.v1.HealthResponse
	(*CapabilitiesResponse)(nil),   // 35: connector.v1.CapabilitiesResponse
}
var file_credentialloader_proto_depIdxs = []int32{
	1,  // 0: connector.v1.ResolveRequest.ref:type_name -> connector.v1.Ref
	2,  // 1: connector.v1.ResolveResponse.material:type_name -> connector.v1.Material
	1,  // 2: connector.v1.ListResponse.refs:type_name -> connector.v1.Ref
	1,  // 3: connector.v1.LeaseRequest.ref:type_name -> connector.v1.Ref
	2,  // 4: connector.v1.LeaseResponse.material:type_name -> connector.v1.Material
	3,  // 5: connector.v1.LeaseResponse.lease:type_name -> connector.v1.Lease
	3,  // 6: connector.v1.RenewRequest.lease:type_name -> connector.v1.Lease
	3,  // 7: connector.v1.RenewResponse.lease:type_name -> connector.v1.Lease
	3,  // 8: connector.v1.RevokeRequest.lease:type_name -> connector.v1.Lease
	16, // 9: connector.v1.BindAuthRequest.keys:type_name -> connector.v1.BootstrapEntry
	1,  // 10: connector.v1.ResolveBatchRequest.refs:type_name -> connector.v1.Ref
	1,  // 11: connector.v1.ResolveBatchResult.ref:type_name -> connector.v1.Ref
	2,  // 12: connector.v1.ResolveBatchResult.material:type_name -> connector.v1.Material
	4,  // 13: connector.v1.ResolveBatchResult.failure:type_name -> connector.v1.Failure
	19, // 14: connector.v1.ResolveBatchResponse.results:type_name -> connector.v1.ResolveBatchResult
	21, // 15: connector.v1.AuthStatusResponse.session:type_name -> connector.v1.AuthSession
	21, // 16: connector.v1.RenewAuthRequest.session:type_name -> connector.v1.AuthSession
	21, // 17: connector.v1.RenewAuthResponse.session:type_name -> connector.v1.AuthSession
	15, // 18: connector.v1.ReauthenticateRequest.bootstrap:type_name -> connector.v1.BindAuthRequest
	21, // 19: connector.v1.ReauthenticateResponse.session:type_name -> connector.v1.AuthSession
	1,  // 20: connector.v1.GrantInventory.keys:type_name -> connector.v1.Ref
	1,  // 21: connector.v1.BundleEntry.identity:type_name -> connector.v1.Ref
	2,  // 22: connector.v1.BundleEntry.material:type_name -> connector.v1.Material
	28, // 23: connector.v1.AcquireBundleRequest.inventory:type_name -> connector.v1.GrantInventory
	29, // 24: connector.v1.AcquireBundleResponse.entries:type_name -> connector.v1.BundleEntry
	0,  // 25: connector.v1.AcquireBundleResponse.completeness:type_name -> connector.v1.BundleCompleteness
	5,  // 26: connector.v1.CredentialLoader.Resolve:input_type -> connector.v1.ResolveRequest
	7,  // 27: connector.v1.CredentialLoader.List:input_type -> connector.v1.ListRequest
	9,  // 28: connector.v1.CredentialLoader.Lease:input_type -> connector.v1.LeaseRequest
	11, // 29: connector.v1.CredentialLoader.Renew:input_type -> connector.v1.RenewRequest
	13, // 30: connector.v1.CredentialLoader.Revoke:input_type -> connector.v1.RevokeRequest
	32, // 31: connector.v1.CredentialLoader.Health:input_type -> connector.v1.HealthRequest
	33, // 32: connector.v1.CredentialLoader.Capabilities:input_type -> connector.v1.CapabilitiesRequest
	18, // 33: connector.v1.CredentialLoader.ResolveBatch:input_type -> connector.v1.ResolveBatchRequest
	15, // 34: connector.v1.CredentialLoader.BindAuth:input_type -> connector.v1.BindAuthRequest
	30, // 35: connector.v1.CredentialLoader.AcquireBundle:input_type -> connector.v1.AcquireBundleRequest
	22, // 36: connector.v1.CredentialLoader.AuthStatus:input_type -> connector.v1.AuthStatusRequest
	24, // 37: connector.v1.CredentialLoader.RenewAuth:input_type -> connector.v1.RenewAuthRequest
	26, // 38: connector.v1.CredentialLoader.Reauthenticate:input_type -> connector.v1.ReauthenticateRequest
	6,  // 39: connector.v1.CredentialLoader.Resolve:output_type -> connector.v1.ResolveResponse
	8,  // 40: connector.v1.CredentialLoader.List:output_type -> connector.v1.ListResponse
	10, // 41: connector.v1.CredentialLoader.Lease:output_type -> connector.v1.LeaseResponse
	12, // 42: connector.v1.CredentialLoader.Renew:output_type -> connector.v1.RenewResponse
	14, // 43: connector.v1.CredentialLoader.Revoke:output_type -> connector.v1.RevokeResponse
	34, // 44: connector.v1.CredentialLoader.Health:output_type -> connector.v1.HealthResponse
	35, // 45: connector.v1.CredentialLoader.Capabilities:output_type -> connector.v1.CapabilitiesResponse
	20, // 46: connector.v1.CredentialLoader.ResolveBatch:output_type -> connector.v1.ResolveBatchResponse
	17, // 47: connector.v1.CredentialLoader.BindAuth:output_type -> connector.v1.BindAuthResponse
	31, // 48: connector.v1.CredentialLoader.AcquireBundle:output_type -> connector.v1.AcquireBundleResponse
	23, // 49: connector.v1.CredentialLoader.AuthStatus:output_type -> connector.v1.AuthStatusResponse
	25, // 50: connector.v1.CredentialLoader.RenewAuth:output_type -> connector.v1.RenewAuthResponse
	27, // 51: connector.v1.CredentialLoader.Reauthenticate:output_type -> connector.v1.ReauthenticateResponse
	39, // [39:52] is the sub-list for method output_type
	26, // [26:39] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_credentialloader_proto_init() }
func file_credentialloader_proto_init() {
	if File_credentialloader_proto != nil {
		return
	}
	file_connector_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credentialloader_proto_rawDesc), len(file_credentialloader_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credentialloader_proto_goTypes,
		DependencyIndexes: file_credentialloader_proto_depIdxs,
		EnumInfos:         file_credentialloader_proto_enumTypes,
		MessageInfos:      file_credentialloader_proto_msgTypes,
	}.Build()
	File_credentialloader_proto = out.File
	file_credentialloader_proto_goTypes = nil
	file_credentialloader_proto_depIdxs = nil
}
