// The Track-B wire contract for the arqtos Roster connector class: a READ-ONLY
// view of a directory's principals, its groups, and the memberships between
// them.
//
// This file is the contract for provider authors who will never read the Go
// SDK — including authors writing in another language. Everything a host relies
// on is stated here, in this file, rather than only in the Go doc comments of
// the reference implementation. If the two ever disagree, this file is what the
// wire actually carries.
//
// # The one rule that matters most
//
// A directory read that DID NOT RESOLVE must never reach a host looking like a
// directory that is genuinely empty.
//
// This is the same conflation the CredentialLoader contract refuses for an
// empty secret, and it is deliberately the SAME SHAPE here rather than a second
// invention — but the blast radius is worse. A credential that resolves to ""
// fails one authentication. A roster that reads as nobody removes everyone's
// access at once: a host sweeping for departed people computes "in arqtos, no
// longer in the directory" and revokes it, so an empty list that actually meant
// "the read failed" deprovisions the entire estate — correctly, according to
// everything the host was told.
//
// A protobuf `repeated` field DEFAULTS TO EMPTY, and proto3 does not put an
// empty repeated field on the wire at all. So a list mapped straight onto a
// bare `repeated` field cannot express the difference: "I read the directory
// and found nobody" and "I did not read the directory" are the same bytes. That
// is why every list here travels inside its own message, and why that message
// carries an assertion flag. See PrincipalRoster below.
//
// # There is no way to say "partial"
//
// A read that stopped before covering everything it is meant to — a paginated
// listing that failed on page 7 of 250 — is NOT expressible as a success on
// this wire, deliberately. It is a typed failure: return a gRPC status error
// (UNAVAILABLE, DEADLINE_EXCEEDED, RESOURCE_EXHAUSTED as applicable). A host
// cannot safely revoke access for a principal the connector never got to
// examine, so a truncated read must not arrive as a smaller success. Sending
// what you managed to collect, with no indication it is incomplete, is the same
// failure as the one above with a smaller radius: the sweep revokes everyone
// past the point your pagination broke.
//
// # Watch is not on this wire
//
// The Roster class has an optional watch capability (push notification of
// directory change) in its Go contract. It has no RPC here, so an
// out-of-process provider CANNOT declare it and must be polled. Polling is the
// fallback that capability's own contract already defines for a connector
// without it — correctness lives in the host's reconcile loop either way, and
// an event only makes it converge sooner.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: roster.proto

package connectorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Roster_ListPrincipals_FullMethodName  = "/connector.v1.Roster/ListPrincipals"
	Roster_ListGroups_FullMethodName      = "/connector.v1.Roster/ListGroups"
	Roster_ListMemberships_FullMethodName = "/connector.v1.Roster/ListMemberships"
	Roster_Health_FullMethodName          = "/connector.v1.Roster/Health"
	Roster_Capabilities_FullMethodName    = "/connector.v1.Roster/Capabilities"
	Roster_Close_FullMethodName           = "/connector.v1.Roster/Close"
)

// RosterClient is the client API for Roster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Roster is the out-of-process (Track-B) service a directory provider serves
// and a host dials. It mirrors the roster.Roster Go interface 1:1.
//
// # Read-only, on purpose
//
// There is no Create, no Update, no Delete, and none is coming. arqtos
// provisions arqtos-side artifacts; it does not create people in someone
// else's directory. A class that could write to a directory would make every
// reconcile bug a destructive one.
//
// # Errors
//
// Every failure is a gRPC status error whose CODE carries the classification —
// a host acts on the code, never on the message text:
//
//	NOT_FOUND           the group asked about does not exist
//	PERMISSION_DENIED   no access, including a backend session not signed in
//	UNAVAILABLE         the directory is transiently unreachable
//	UNIMPLEMENTED       this connector does not support the operation
//	INVALID_ARGUMENT    malformed input
//	DEADLINE_EXCEEDED   the operation timed out
//	RESOURCE_EXHAUSTED  the directory reported a quota or rate limit
//	INTERNAL            reserved for host-detected contract violations
//	UNKNOWN             the provider could not classify the failure
//
// Error MESSAGES cross the wire verbatim and may be logged by the host, so
// they MUST NOT contain directory records about identifiable people.
type RosterClient interface {
	// ListPrincipals returns EVERY identity in the directory this connector
	// serves, INCLUDING deactivated ones (with Principal.active = false).
	ListPrincipals(ctx context.Context, in *ListPrincipalsRequest, opts ...grpc.CallOption) (*ListPrincipalsResponse, error)
	// ListGroups returns every group in the directory this connector serves.
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	// ListMemberships returns the memberships of the SINGLE group named by
	// group_id.
	//
	// Two things about it are refused by the host rather than merely documented:
	//
	//   - every returned Membership.group_id MUST equal the requested group_id;
	//   - a group that does not exist is NOT_FOUND, not an empty roster.
	//
	// The second is the one that looks harmless. "This group has no members" and
	// "there is no such group" lead a reconcile loop to opposite conclusions:
	// given the first for the second, it removes the access that group carried.
	ListMemberships(ctx context.Context, in *ListMembershipsRequest, opts ...grpc.CallOption) (*ListMembershipsResponse, error)
	// Health reports reachability of the directory.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Capabilities lists what this connector supports, from the Roster class's
	// closed vocabulary: "watch", "transitive_membership",
	// "machine_principals". A host reads this ONCE, at dial time.
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// Close releases what the provider holds — a session against someone else's
	// directory API, typically. It is idempotent, and it is not process
	// teardown: the host owns that, by killing the process.
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
}

type rosterClient struct {
	cc grpc.ClientConnInterface
}

func NewRosterClient(cc grpc.ClientConnInterface) RosterClient {
	return &rosterClient{cc}
}

func (c *rosterClient) ListPrincipals(ctx context.Context, in *ListPrincipalsRequest, opts ...grpc.CallOption) (*ListPrincipalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPrincipalsResponse)
	err := c.cc.Invoke(ctx, Roster_ListPrincipals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosterClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, Roster_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosterClient) ListMemberships(ctx context.Context, in *ListMembershipsRequest, opts ...grpc.CallOption) (*ListMembershipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembershipsResponse)
	err := c.cc.Invoke(ctx, Roster_ListMemberships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosterClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Roster_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosterClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, Roster_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rosterClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, Roster_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RosterServer is the server API for Roster service.
// All implementations must embed UnimplementedRosterServer
// for forward compatibility.
//
// Roster is the out-of-process (Track-B) service a directory provider serves
// and a host dials. It mirrors the roster.Roster Go interface 1:1.
//
// # Read-only, on purpose
//
// There is no Create, no Update, no Delete, and none is coming. arqtos
// provisions arqtos-side artifacts; it does not create people in someone
// else's directory. A class that could write to a directory would make every
// reconcile bug a destructive one.
//
// # Errors
//
// Every failure is a gRPC status error whose CODE carries the classification —
// a host acts on the code, never on the message text:
//
//	NOT_FOUND           the group asked about does not exist
//	PERMISSION_DENIED   no access, including a backend session not signed in
//	UNAVAILABLE         the directory is transiently unreachable
//	UNIMPLEMENTED       this connector does not support the operation
//	INVALID_ARGUMENT    malformed input
//	DEADLINE_EXCEEDED   the operation timed out
//	RESOURCE_EXHAUSTED  the directory reported a quota or rate limit
//	INTERNAL            reserved for host-detected contract violations
//	UNKNOWN             the provider could not classify the failure
//
// Error MESSAGES cross the wire verbatim and may be logged by the host, so
// they MUST NOT contain directory records about identifiable people.
type RosterServer interface {
	// ListPrincipals returns EVERY identity in the directory this connector
	// serves, INCLUDING deactivated ones (with Principal.active = false).
	ListPrincipals(context.Context, *ListPrincipalsRequest) (*ListPrincipalsResponse, error)
	// ListGroups returns every group in the directory this connector serves.
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	// ListMemberships returns the memberships of the SINGLE group named by
	// group_id.
	//
	// Two things about it are refused by the host rather than merely documented:
	//
	//   - every returned Membership.group_id MUST equal the requested group_id;
	//   - a group that does not exist is NOT_FOUND, not an empty roster.
	//
	// The second is the one that looks harmless. "This group has no members" and
	// "there is no such group" lead a reconcile loop to opposite conclusions:
	// given the first for the second, it removes the access that group carried.
	ListMemberships(context.Context, *ListMembershipsRequest) (*ListMembershipsResponse, error)
	// Health reports reachability of the directory.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Capabilities lists what this connector supports, from the Roster class's
	// closed vocabulary: "watch", "transitive_membership",
	// "machine_principals". A host reads this ONCE, at dial time.
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	// Close releases what the provider holds — a session against someone else's
	// directory API, typically. It is idempotent, and it is not process
	// teardown: the host owns that, by killing the process.
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	mustEmbedUnimplementedRosterServer()
}

// UnimplementedRosterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRosterServer struct{}

func (UnimplementedRosterServer) ListPrincipals(context.Context, *ListPrincipalsRequest) (*ListPrincipalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPrincipals not implemented")
}
func (UnimplementedRosterServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedRosterServer) ListMemberships(context.Context, *ListMembershipsRequest) (*ListMembershipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemberships not implemented")
}
func (UnimplementedRosterServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRosterServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedRosterServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedRosterServer) mustEmbedUnimplementedRosterServer() {}
func (UnimplementedRosterServer) testEmbeddedByValue()                {}

// UnsafeRosterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RosterServer will
// result in compilation errors.
type UnsafeRosterServer interface {
	mustEmbedUnimplementedRosterServer()
}

func RegisterRosterServer(s grpc.ServiceRegistrar, srv RosterServer) {
	// If the following call panics, it indicates UnimplementedRosterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Roster_ServiceDesc, srv)
}

func _Roster_ListPrincipals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPrincipalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosterServer).ListPrincipals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Roster_ListPrincipals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosterServer).ListPrincipals(ctx, req.(*ListPrincipalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roster_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosterServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Roster_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosterServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roster_ListMemberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembershipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosterServer).ListMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Roster_ListMemberships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosterServer).ListMemberships(ctx, req.(*ListMembershipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roster_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosterServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Roster_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosterServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roster_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosterServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Roster_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosterServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roster_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosterServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Roster_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosterServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Roster_ServiceDesc is the grpc.ServiceDesc for Roster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Roster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connector.v1.Roster",
	HandlerType: (*RosterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPrincipals",
			Handler:    _Roster_ListPrincipals_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _Roster_ListGroups_Handler,
		},
		{
			MethodName: "ListMemberships",
			Handler:    _Roster_ListMemberships_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Roster_Health_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _Roster_Capabilities_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Roster_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roster.proto",
}
