// The Track-B wire contract for the arqtos Roster connector class: a READ-ONLY
// view of a directory's principals, its groups, and the memberships between
// them.
//
// This file is the contract for provider authors who will never read the Go
// SDK — including authors writing in another language. Everything a host relies
// on is stated here, in this file, rather than only in the Go doc comments of
// the reference implementation. If the two ever disagree, this file is what the
// wire actually carries.
//
// # The one rule that matters most
//
// A directory read that DID NOT RESOLVE must never reach a host looking like a
// directory that is genuinely empty.
//
// This is the same conflation the CredentialLoader contract refuses for an
// empty secret, and it is deliberately the SAME SHAPE here rather than a second
// invention — but the blast radius is worse. A credential that resolves to ""
// fails one authentication. A roster that reads as nobody removes everyone's
// access at once: a host sweeping for departed people computes "in arqtos, no
// longer in the directory" and revokes it, so an empty list that actually meant
// "the read failed" deprovisions the entire estate — correctly, according to
// everything the host was told.
//
// A protobuf `repeated` field DEFAULTS TO EMPTY, and proto3 does not put an
// empty repeated field on the wire at all. So a list mapped straight onto a
// bare `repeated` field cannot express the difference: "I read the directory
// and found nobody" and "I did not read the directory" are the same bytes. That
// is why every list here travels inside its own message, and why that message
// carries an assertion flag. See PrincipalRoster below.
//
// # There is no way to say "partial"
//
// A read that stopped before covering everything it is meant to — a paginated
// listing that failed on page 7 of 250 — is NOT expressible as a success on
// this wire, deliberately. It is a typed failure: return a gRPC status error
// (UNAVAILABLE, DEADLINE_EXCEEDED, RESOURCE_EXHAUSTED as applicable). A host
// cannot safely revoke access for a principal the connector never got to
// examine, so a truncated read must not arrive as a smaller success. Sending
// what you managed to collect, with no indication it is incomplete, is the same
// failure as the one above with a smaller radius: the sweep revokes everyone
// past the point your pagination broke.
//
// # Watch is not on this wire
//
// The Roster class has an optional watch capability (push notification of
// directory change) in its Go contract. It has no RPC here, so an
// out-of-process provider CANNOT declare it and must be polled. Polling is the
// fallback that capability's own contract already defines for a connector
// without it — correctness lives in the host's reconcile loop either way, and
// an event only makes it converge sooner.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: roster.proto

package connectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Principal is ONE identity as the directory holds it.
//
// Every field is a directory fact. None of them is an arqtos concept: there is
// no org, no team, no role and no entitlement here, because the moment a
// connector reports one of those it has started deciding host policy from
// inside a vendor adapter.
type Principal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The directory's STABLE identifier — the one that survives a rename and a
	// change of address. NOT the email: email changes, and a host that keyed on
	// it treats a renamed person as a departed person plus a new hire, the first
	// half of which is a full deprovision.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The login as the directory spells it, unnormalised. For display and for
	// correlating with vendor UIs — not for identity.
	Handle string `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	// MAY be empty, and an empty one is not an error: machine identities
	// frequently have no mailbox, and some directories hold people with no
	// address either.
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Whether the directory considers this identity currently enabled.
	//
	// A DEACTIVATED IDENTITY IS STILL REPORTED, with active = false. It has not
	// left the directory, and a host that sees it disappear concludes that it
	// has — then revokes everything belonging to someone who is suspended, on
	// leave, or mid-transfer. Absence from the list means absence from the
	// DIRECTORY; this field is how "present but disabled" is said.
	//
	// Note that false is proto3's default for a bool, so this is the field a
	// careless mapping loses without any error anywhere. Losing it in the other
	// direction — reporting a suspended person as active — means their access is
	// never withdrawn.
	Active bool `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	// What sort of identity this is: 0 = unknown, 1 = human, 2 = machine. It
	// carries the numbering of the Go PrincipalKind vocabulary, which is the
	// single source for the closed set.
	//
	// 0 (unknown) is the safe default: a connector that has not classified an
	// identity says so, and a host that treats machine identities differently
	// from human ones then knows it must apply neither rule. A number outside
	// this set is read as 0 rather than guessed at.
	//
	// Reporting a machine principal (2) requires the "machine_principals"
	// capability. A host refuses one from a connector that has not declared it:
	// the declaration is what makes the ABSENCE of machine principals readable
	// as a fact about the directory rather than a limit of the connector.
	Kind          int32 `protobuf:"varint,6,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_roster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{0}
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Principal) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Principal) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Principal) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Principal) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Principal) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

// Group is ONE group as the directory holds it.
type Group struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The directory's stable identifier, for the same reason Principal.id is.
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Handle      string `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The groups this group is nested inside, where the directory supports
	// nesting. Empty for a flat directory, and that emptiness is not a failure.
	ParentIds     []string `protobuf:"bytes,4,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_roster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{1}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Group) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Group) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

// Membership is ONE principal's membership of ONE group.
type Membership struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member's Principal.id.
	//
	// It need not name a principal from ListPrincipals: some directories admit
	// groups as members of groups, and external or guest identities a directory
	// read does not enumerate. A host resolves what it recognises and reports
	// what it does not; it must not treat an unrecognised member as an absent
	// one.
	PrincipalId string `protobuf:"bytes,1,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	// The Group.id this membership is in.
	//
	// Every membership in a ListMemberships response MUST carry the group id
	// that was REQUESTED. A host refuses the whole response otherwise: it cannot
	// attribute an entry for a group it did not ask about, and guessing the
	// correspondence is how the wrong people end up in the wrong group.
	GroupId string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Whether the membership is held directly. false means INHERITED through
	// group nesting, and reporting an inherited membership requires the
	// "transitive_membership" capability — a host refuses one from a connector
	// that has not declared it, for the same reason as machine principals.
	Direct        bool `protobuf:"varint,3,opt,name=direct,proto3" json:"direct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_roster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{2}
}

func (x *Membership) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *Membership) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Membership) GetDirect() bool {
	if x != nil {
		return x.Direct
	}
	return false
}

// PrincipalRoster is a resolved list of principals, and the presence rules
// below are this contract's load-bearing part. GroupRoster and
// MembershipRoster below are the same three rules for the other two lists —
// read this comment for all three.
//
// Read the four cases as a WHOLE MESSAGE, not as a repeated field:
//
//  1. NO PrincipalRoster message at all (the containing field is unset)
//     -> nothing was resolved. The host treats this as a failure and refuses
//     to produce a readable roster from it.
//
//  2. PrincipalRoster with one or more `principals`
//     -> that is the directory's list. `empty_by_assertion` is ignored here;
//     entries present always mean a resolved list.
//
//  3. PrincipalRoster with NO `principals` AND `empty_by_assertion = true`
//     -> the provider ASSERTS the directory genuinely holds nobody. The host
//     produces a readable roster of length zero.
//
//  4. PrincipalRoster with no `principals` and NO `empty_by_assertion`
//     -> nothing was resolved. Identical to case 1. This is deliberate: it is
//     the encoding a provider produces by ACCIDENT (an unset struct, a
//     default-constructed message, an empty slice it forwarded from a
//     failed backend call), and the accidental encoding must have the SAFE
//     meaning.
//
// proto3 does not put an empty repeated field on the wire at all, so cases 3
// and 4 differ ONLY by the boolean. That is exactly why the boolean exists:
// without it, a conformant "genuinely empty directory" and a rogue "I read
// nothing" are byte-identical and the host cannot tell them apart — at which
// point every host must choose one meaning for both, and either choice is
// wrong for the other case.
//
// Set empty_by_assertion ONLY if your backend can distinguish a SUCCESSFUL
// READ THAT FOUND NOTHING from an unauthenticated, throttled, misdirected or
// failed one. If it cannot make that distinction, you have a failure on your
// hands, not an empty directory: return a gRPC status error instead.
type PrincipalRoster struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Principals       []*Principal           `protobuf:"bytes,1,rep,name=principals,proto3" json:"principals,omitempty"`
	EmptyByAssertion bool                   `protobuf:"varint,2,opt,name=empty_by_assertion,json=emptyByAssertion,proto3" json:"empty_by_assertion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrincipalRoster) Reset() {
	*x = PrincipalRoster{}
	mi := &file_roster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrincipalRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalRoster) ProtoMessage() {}

func (x *PrincipalRoster) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalRoster.ProtoReflect.Descriptor instead.
func (*PrincipalRoster) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{3}
}

func (x *PrincipalRoster) GetPrincipals() []*Principal {
	if x != nil {
		return x.Principals
	}
	return nil
}

func (x *PrincipalRoster) GetEmptyByAssertion() bool {
	if x != nil {
		return x.EmptyByAssertion
	}
	return false
}

// GroupRoster is a resolved list of groups. Same presence rules as
// PrincipalRoster — read its comment.
type GroupRoster struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Groups           []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	EmptyByAssertion bool                   `protobuf:"varint,2,opt,name=empty_by_assertion,json=emptyByAssertion,proto3" json:"empty_by_assertion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupRoster) Reset() {
	*x = GroupRoster{}
	mi := &file_roster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRoster) ProtoMessage() {}

func (x *GroupRoster) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRoster.ProtoReflect.Descriptor instead.
func (*GroupRoster) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{4}
}

func (x *GroupRoster) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GroupRoster) GetEmptyByAssertion() bool {
	if x != nil {
		return x.EmptyByAssertion
	}
	return false
}

// MembershipRoster is a resolved list of memberships. Same presence rules as
// PrincipalRoster — read its comment.
//
// A newly created group with no members is the ordinary case for
// `empty_by_assertion` here, and it is a state a host must be able to see: the
// access that group carried has to come off. What it is not is somewhere to
// put a failed read.
type MembershipRoster struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Memberships      []*Membership          `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	EmptyByAssertion bool                   `protobuf:"varint,2,opt,name=empty_by_assertion,json=emptyByAssertion,proto3" json:"empty_by_assertion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MembershipRoster) Reset() {
	*x = MembershipRoster{}
	mi := &file_roster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipRoster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipRoster) ProtoMessage() {}

func (x *MembershipRoster) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipRoster.ProtoReflect.Descriptor instead.
func (*MembershipRoster) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{5}
}

func (x *MembershipRoster) GetMemberships() []*Membership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

func (x *MembershipRoster) GetEmptyByAssertion() bool {
	if x != nil {
		return x.EmptyByAssertion
	}
	return false
}

type ListPrincipalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrincipalsRequest) Reset() {
	*x = ListPrincipalsRequest{}
	mi := &file_roster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrincipalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrincipalsRequest) ProtoMessage() {}

func (x *ListPrincipalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrincipalsRequest.ProtoReflect.Descriptor instead.
func (*ListPrincipalsRequest) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{6}
}

// ListPrincipalsResponse carries the directory's identities, subject to
// PrincipalRoster's presence rules. An UNSET roster field means nothing was
// resolved; returning a gRPC status error is better still, because it also
// says WHY.
type ListPrincipalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roster        *PrincipalRoster       `protobuf:"bytes,1,opt,name=roster,proto3" json:"roster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrincipalsResponse) Reset() {
	*x = ListPrincipalsResponse{}
	mi := &file_roster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrincipalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrincipalsResponse) ProtoMessage() {}

func (x *ListPrincipalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrincipalsResponse.ProtoReflect.Descriptor instead.
func (*ListPrincipalsResponse) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{7}
}

func (x *ListPrincipalsResponse) GetRoster() *PrincipalRoster {
	if x != nil {
		return x.Roster
	}
	return nil
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_roster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{8}
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roster        *GroupRoster           `protobuf:"bytes,1,opt,name=roster,proto3" json:"roster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_roster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{9}
}

func (x *ListGroupsResponse) GetRoster() *GroupRoster {
	if x != nil {
		return x.Roster
	}
	return nil
}

type ListMembershipsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The group whose members are wanted. A group that DOES NOT EXIST is
	// NOT_FOUND, never an empty roster — see the service comment below.
	GroupId       string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipsRequest) Reset() {
	*x = ListMembershipsRequest{}
	mi := &file_roster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipsRequest) ProtoMessage() {}

func (x *ListMembershipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipsRequest.ProtoReflect.Descriptor instead.
func (*ListMembershipsRequest) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{10}
}

func (x *ListMembershipsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ListMembershipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roster        *MembershipRoster      `protobuf:"bytes,1,opt,name=roster,proto3" json:"roster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembershipsResponse) Reset() {
	*x = ListMembershipsResponse{}
	mi := &file_roster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembershipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembershipsResponse) ProtoMessage() {}

func (x *ListMembershipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembershipsResponse.ProtoReflect.Descriptor instead.
func (*ListMembershipsResponse) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{11}
}

func (x *ListMembershipsResponse) GetRoster() *MembershipRoster {
	if x != nil {
		return x.Roster
	}
	return nil
}

var File_roster_proto protoreflect.FileDescriptor

const file_roster_proto_rawDesc = "" +
	"\n" +
	"\froster.proto\x12\fconnector.v1\x1a\x0fconnector.proto\"\x98\x01\n" +
	"\tPrincipal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\x05R\x04kind\"q\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x04 \x03(\tR\tparentIds\"b\n" +
	"\n" +
	"Membership\x12!\n" +
	"\fprincipal_id\x18\x01 \x01(\tR\vprincipalId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x16\n" +
	"\x06direct\x18\x03 \x01(\bR\x06direct\"x\n" +
	"\x0fPrincipalRoster\x127\n" +
	"\n" +
	"principals\x18\x01 \x03(\v2\x17.connector.v1.PrincipalR\n" +
	"principals\x12,\n" +
	"\x12empty_by_assertion\x18\x02 \x01(\bR\x10emptyByAssertion\"h\n" +
	"\vGroupRoster\x12+\n" +
	"\x06groups\x18\x01 \x03(\v2\x13.connector.v1.GroupR\x06groups\x12,\n" +
	"\x12empty_by_assertion\x18\x02 \x01(\bR\x10emptyByAssertion\"|\n" +
	"\x10MembershipRoster\x12:\n" +
	"\vmemberships\x18\x01 \x03(\v2\x18.connector.v1.MembershipR\vmemberships\x12,\n" +
	"\x12empty_by_assertion\x18\x02 \x01(\bR\x10emptyByAssertion\"\x17\n" +
	"\x15ListPrincipalsRequest\"O\n" +
	"\x16ListPrincipalsResponse\x125\n" +
	"\x06roster\x18\x01 \x01(\v2\x1d.connector.v1.PrincipalRosterR\x06roster\"\x13\n" +
	"\x11ListGroupsRequest\"G\n" +
	"\x12ListGroupsResponse\x121\n" +
	"\x06roster\x18\x01 \x01(\v2\x19.connector.v1.GroupRosterR\x06roster\"3\n" +
	"\x16ListMembershipsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"Q\n" +
	"\x17ListMembershipsResponse\x126\n" +
	"\x06roster\x18\x01 \x01(\v2\x1e.connector.v1.MembershipRosterR\x06roster2\xf4\x03\n" +
	"\x06Roster\x12[\n" +
	"\x0eListPrincipals\x12#.connector.v1.ListPrincipalsRequest\x1a$.connector.v1.ListPrincipalsResponse\x12O\n" +
	"\n" +
	"ListGroups\x12\x1f.connector.v1.ListGroupsRequest\x1a .connector.v1.ListGroupsResponse\x12^\n" +
	"\x0fListMemberships\x12$.connector.v1.ListMembershipsRequest\x1a%.connector.v1.ListMembershipsResponse\x12C\n" +
	"\x06Health\x12\x1b.connector.v1.HealthRequest\x1a\x1c.connector.v1.HealthResponse\x12U\n" +
	"\fCapabilities\x12!.connector.v1.CapabilitiesRequest\x1a\".connector.v1.CapabilitiesResponse\x12@\n" +
	"\x05Close\x12\x1a.connector.v1.CloseRequest\x1a\x1b.connector.v1.CloseResponseB.Z,github.com/arqtiqa/arqtos-sdk-go/connectorpbb\x06proto3"

var (
	file_roster_proto_rawDescOnce sync.Once
	file_roster_proto_rawDescData []byte
)

func file_roster_proto_rawDescGZIP() []byte {
	file_roster_proto_rawDescOnce.Do(func() {
		file_roster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_roster_proto_rawDesc), len(file_roster_proto_rawDesc)))
	})
	return file_roster_proto_rawDescData
}

var file_roster_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_roster_proto_goTypes = []any{
	(*Principal)(nil),               // 0: connector.v1.Principal
	(*Group)(nil),                   // 1: connector.v1.Group
	(*Membership)(nil),              // 2: connector.v1.Membership
	(*PrincipalRoster)(nil),         // 3: connector.v1.PrincipalRoster
	(*GroupRoster)(nil),             // 4: connector.v1.GroupRoster
	(*MembershipRoster)(nil),        // 5: connector.v1.MembershipRoster
	(*ListPrincipalsRequest)(nil),   // 6: connector.v1.ListPrincipalsRequest
	(*ListPrincipalsResponse)(nil),  // 7: connector.v1.ListPrincipalsResponse
	(*ListGroupsRequest)(nil),       // 8: connector.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),      // 9: connector.v1.ListGroupsResponse
	(*ListMembershipsRequest)(nil),  // 10: connector.v1.ListMembershipsRequest
	(*ListMembershipsResponse)(nil), // 11: connector.v1.ListMembershipsResponse
	(*HealthRequest)(nil),           // 12: connector.v1.HealthRequest
	(*CapabilitiesRequest)(nil),     // 13: connector.v1.CapabilitiesRequest
	(*CloseRequest)(nil),            // 14: connector.v1.CloseRequest
	(*HealthResponse)(nil),          // 15: connector.v1.HealthResponse
	(*CapabilitiesResponse)(nil),    // 16: connector.v1.CapabilitiesResponse
	(*CloseResponse)(nil),           // 17: connector.v1.CloseResponse
}
var file_roster_proto_depIdxs = []int32{
	0,  // 0: connector.v1.PrincipalRoster.principals:type_name -> connector.v1.Principal
	1,  // 1: connector.v1.GroupRoster.groups:type_name -> connector.v1.Group
	2,  // 2: connector.v1.MembershipRoster.memberships:type_name -> connector.v1.Membership
	3,  // 3: connector.v1.ListPrincipalsResponse.roster:type_name -> connector.v1.PrincipalRoster
	4,  // 4: connector.v1.ListGroupsResponse.roster:type_name -> connector.v1.GroupRoster
	5,  // 5: connector.v1.ListMembershipsResponse.roster:type_name -> connector.v1.MembershipRoster
	6,  // 6: connector.v1.Roster.ListPrincipals:input_type -> connector.v1.ListPrincipalsRequest
	8,  // 7: connector.v1.Roster.ListGroups:input_type -> connector.v1.ListGroupsRequest
	10, // 8: connector.v1.Roster.ListMemberships:input_type -> connector.v1.ListMembershipsRequest
	12, // 9: connector.v1.Roster.Health:input_type -> connector.v1.HealthRequest
	13, // 10: connector.v1.Roster.Capabilities:input_type -> connector.v1.CapabilitiesRequest
	14, // 11: connector.v1.Roster.Close:input_type -> connector.v1.CloseRequest
	7,  // 12: connector.v1.Roster.ListPrincipals:output_type -> connector.v1.ListPrincipalsResponse
	9,  // 13: connector.v1.Roster.ListGroups:output_type -> connector.v1.ListGroupsResponse
	11, // 14: connector.v1.Roster.ListMemberships:output_type -> connector.v1.ListMembershipsResponse
	15, // 15: connector.v1.Roster.Health:output_type -> connector.v1.HealthResponse
	16, // 16: connector.v1.Roster.Capabilities:output_type -> connector.v1.CapabilitiesResponse
	17, // 17: connector.v1.Roster.Close:output_type -> connector.v1.CloseResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_roster_proto_init() }
func file_roster_proto_init() {
	if File_roster_proto != nil {
		return
	}
	file_connector_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_roster_proto_rawDesc), len(file_roster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roster_proto_goTypes,
		DependencyIndexes: file_roster_proto_depIdxs,
		MessageInfos:      file_roster_proto_msgTypes,
	}.Build()
	File_roster_proto = out.File
	file_roster_proto_goTypes = nil
	file_roster_proto_depIdxs = nil
}
